
-- Generated by ORDS REST Data Services 26.2.0.r1732140
-- Schema: WKSP_SINDICATTO  Date: Wed Jul 08 05:04:42 2026 
--
        
DECLARE

  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'wksp_sindicatto',
      p_auto_rest_auth      => FALSE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'public',
      p_base_path      => '/public/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'public',
      p_pattern        => 'news/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'public',
      p_pattern        => 'news/:id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT c.id
    , c.tenant_code
    , c.ctype_code
    , c.title
    , c.contents
    , c.created_at
    , c.updated_at
    , c.published_at
    , c.image_alt
    , CASE WHEN c.image_url IS NOT NULL THEN c.image_url
           WHEN c.image_blob IS NOT NULL THEN
               ''/ords/wksp_sindicatto/api/content-image/'' || c.id ||
               ''?v='' || to_char(nvl(c.image_updated_at, c.updated_at), ''YYYYMMDDHH24MISS'')
    END AS image_url
    , ct.name AS ctype_name

FROM content c
left join ctype ct on lower(ct.tenant_code) = lower(c.tenant_code) and lower(ct.code) = lower(c.ctype_code)
WHERE c.id = :id

ORDER BY c.published_at DESC');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'public',
      p_pattern        => 'contents/:code',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'public',
      p_pattern        => 'contents/:code',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT c.id
     , c.tenant_code
     , c.ctype_code
     , c.slug
     , c.sort_order
     , c.status
     , c.title
     , c.contents
     , c.content_format
     , c.created_at
     , c.updated_at
     , c.published_at
     , c.image_alt
     , CASE
           WHEN c.image_url IS NOT NULL THEN
               c.image_url
           WHEN c.image_blob IS NOT NULL THEN
               ''/ords/wksp_sindicatto/api/content-image/'' || c.id ||
               ''?v='' || to_char(nvl(c.image_updated_at, c.updated_at), ''YYYYMMDDHH24MISS'')
       END AS image_url
FROM content c
LEFT JOIN ctype ct
       ON lower(ct.tenant_code) = lower(c.tenant_code)
      AND lower(ct.code) = lower(c.ctype_code)
WHERE lower(c.ctype_code) = lower(:code)
--   AND nvl(c.status, ''published'') = ''published''
ORDER BY nvl(c.sort_order, 999999), c.published_at DESC, c.id DESC');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'public',
      p_pattern        => 'content-image/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'public',
      p_pattern        => 'content-image/:id',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT
    NVL(image_mime_type, ''image/jpeg'') AS content_type,
    image_blob AS content
FROM content
WHERE id = :id
  AND image_blob IS NOT NULL');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'public',
      p_pattern        => 'news',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'public',
      p_pattern        => 'news',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT c.id
    , c.tenant_code
    , c.ctype_code
    , c.title
    , c.contents
    , c.created_at
    , c.updated_at
    , c.published_at
    , c.image_alt
    , CASE WHEN c.image_url IS NOT NULL THEN c.image_url
           WHEN c.image_blob IS NOT NULL THEN
               ''/ords/wksp_sindicatto/api/content-image/'' || c.id ||
               ''?v='' || to_char(nvl(c.image_updated_at, c.updated_at), ''YYYYMMDDHH24MISS'')
    END AS image_url
    , ct.name AS ctype_name

FROM content c
LEFT JOIN ctype ct ON lower(ct.tenant_code) = lower(c.tenant_code) AND lower(ct.code) = lower(c.ctype_code)
WHERE 1 = 1
    AND ctype_code = ''news''
    AND lower(c.tenant_code) = lower(:tenant_code)
-- WHERE c.id = :id

ORDER BY c.published_at DESC');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'public',
      p_pattern            => 'news',
      p_method             => 'GET',
      p_name               => 'tenant_code',
      p_bind_variable_name => 'tenant_code',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;

END;