
-- Generated by ORDS REST Data Services 26.2.0.r1732140
-- Schema: WKSP_SINDICATTO  Date: Fri Jul 10 12:42:11 2026 
--
        
DECLARE

  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'wksp_sindicatto',
      p_auto_rest_auth      => FALSE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'public',
      p_base_path      => '/public/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'public',
      p_pattern        => 'news',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'public',
      p_pattern        => 'news',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT c.id
     , c.tenant_code
     , c.ctype_code
     , c.slug
     , c.sort_order
     , c.status
     , c.title
     , c.contents
     , c.content_format
     , c.author_name
     , c.source_name
     , c.source_url
     , c.created_at
     , c.updated_at
     , c.published_at
     , c.image_alt
     , c.image_filename
     , c.subtype
     , CASE
           WHEN c.image_url IS NOT NULL THEN
               c.image_url
           WHEN c.image_blob IS NOT NULL THEN
               ''/ords/wksp_sindicatto/public/content-image/'' || c.id ||
               ''?v='' || to_char(nvl(c.image_updated_at, c.updated_at), ''YYYYMMDDHH24MISS'')
       END AS image_url
     , ct.name AS ctype_name
FROM content c
LEFT JOIN ctype ct
       ON lower(ct.tenant_code) = lower(c.tenant_code)
      AND lower(ct.code) = lower(c.ctype_code)
WHERE lower(c.ctype_code) = ''news''
  AND (:tenant_code IS NULL OR lower(c.tenant_code) = lower(:tenant_code))
  AND nvl(c.status, ''published'')' || ' = ''published''
ORDER BY c.published_at DESC, c.id DESC
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'public',
      p_pattern            => 'news',
      p_method             => 'GET',
      p_name               => 'tenant_code',
      p_bind_variable_name => 'tenant_code',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'public',
      p_pattern        => 'content-attachments/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'public',
      p_pattern        => 'content-attachments/:id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT *
FROM vw_public_content_attachments_id
WHERE 1 = 1
    AND content_id = :id');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'public',
      p_pattern        => 'news/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'public',
      p_pattern        => 'news/:id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT c.id
     , c.tenant_code
     , c.ctype_code
     , c.slug
     , c.sort_order
     , c.status
     , c.title
     , c.contents
     , c.content_format
     , c.author_name
     , c.source_name
     , c.source_url
     , c.created_at
     , c.updated_at
     , c.published_at
     , c.image_alt
     , c.image_filename
     , c.subtype
     , CASE
           WHEN c.image_url IS NOT NULL THEN
               c.image_url
           WHEN c.image_blob IS NOT NULL THEN
               ''/ords/wksp_sindicatto/public/content-image/'' || c.id ||
               ''?v='' || to_char(nvl(c.image_updated_at, c.updated_at), ''YYYYMMDDHH24MISS'')
       END AS image_url
     , ct.name AS ctype_name
FROM content c
LEFT JOIN ctype ct
       ON lower(ct.tenant_code) = lower(c.tenant_code)
      AND lower(ct.code) = lower(c.ctype_code)
WHERE c.id = :id
  AND (:tenant_code IS NULL OR lower(c.tenant_code) = lower(:tenant_code))
  AND nvl(c.status, ''published'') = ''published''
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'public',
      p_pattern            => 'news/:id',
      p_method             => 'GET',
      p_name               => 'tenant_code',
      p_bind_variable_name => 'tenant_code',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'public',
      p_pattern        => 'contents/:code',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'public',
      p_pattern        => 'contents/:code',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT *
FROM vw_public_content_code
WHERE 1 = 1
    AND lower(ctype_code) = lower(:code)
    AND (:tenant_code IS NULL OR lower(tenant_code) = lower(:tenant_code))
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'public',
      p_pattern            => 'contents/:code',
      p_method             => 'GET',
      p_name               => 'tenant_code',
      p_bind_variable_name => 'tenant_code',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'public',
      p_pattern        => 'content-image/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'public',
      p_pattern        => 'content-image/:id',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT content_type, image
FROM vw_public_content_image_id
WHERE id = :id
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'public',
      p_pattern            => 'content-image/:id',
      p_method             => 'GET',
      p_name               => 'tenant_code',
      p_bind_variable_name => 'tenant_code',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'public',
      p_pattern        => 'content/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'public',
      p_pattern        => 'content/:id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select * from vw_public_content_id
WHERE 1 = 1
    AND id = :id
    AND (:tenant_code IS NULL OR lower(tenant_code) = lower(:tenant_code))');

COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;

END;