-- ignorar checagem
DROP TABLE email_campaign CASCADE CONSTRAINTS;
CREATE TABLE email_campaign (
    id                     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- identificador único da campanha
    tenant_code            VARCHAR2(50)  NOT NULL,
    tenant_id              INTEGER,
    subject                VARCHAR2(500) NOT NULL,                                      -- assunto do e-mail
    body_html              CLOB,                                                        -- corpo do e-mail em HTML
    body_text              CLOB,                                                        -- corpo em texto puro (fallback)
    sender_name            VARCHAR2(255),                                               -- nome do remetente
    sender_email           VARCHAR2(255),                                               -- e-mail do remetente
    send_date              TIMESTAMP,                                                   -- data/hora planejada ou real do envio
    status                 VARCHAR2(20) DEFAULT 'pendente',                             -- pendente | ativo (pronto pra disparo)
    recipient_country_code VARCHAR2(2),                                                 -- 'BR', 'AR', 'VE'
    recipient_uf_code      VARCHAR2(10),                                                -- 'SP', 'C', 'Z'
    created_at             TIMESTAMP    DEFAULT SYSTIMESTAMP,                           -- data de criação
    updated_at             TIMESTAMP,                                                   -- última atualização
    total_emails_sent      NUMBER,
    total_emails_delivered NUMBER,
    opened_percent         NUMBER(5, 2),
    opened_count           NUMBER,
    CONSTRAINT uk_email_campaign_stats UNIQUE (subject, send_date),
    CONSTRAINT fk_campaign_uf FOREIGN KEY (recipient_country_code, recipient_uf_code) REFERENCES country_uf(country_code, code)
);

INSERT INTO email_campaign (tenant_code, subject, sender_name, sender_email, send_date, total_emails_sent, total_emails_delivered, opened_percent, opened_count)
VALUES ('ASACLUB', 'ASAclub & bluefit - Pesquisa de interesse', 'ASAClub', 'naoresponder@asaclub.org.br', TO_TIMESTAMP('2025-07-02 21:46:02', 'YYYY-MM-DD HH24:MI:SS'), 53, 53, 0.00, 0);

INSERT INTO email_campaign (tenant_code, subject, sender_name, sender_email, send_date, total_emails_sent, total_emails_delivered, opened_percent, opened_count)
VALUES ('ASACLUB', 'Exclusivamente para os associados da ASCGU, 5 Vinhos Altano 2021', 'ASAClub', 'naoresponder@asaclub.org.br', TO_TIMESTAMP('2025-06-23 10:01:03', 'YYYY-MM-DD HH24:MI:SS'), 75, 75, 28.00, 21);

INSERT INTO email_campaign (tenant_code, subject, sender_name, sender_email, send_date, total_emails_sent, total_emails_delivered, opened_percent, opened_count)
VALUES ('ASACLUB', 'Vinhos Altano 2021, exclusivamente para os associados da ASCGU', 'ASAClub', 'naoresponder@asaclub.org.br', TO_TIMESTAMP('2025-06-18 10:01:03', 'YYYY-MM-DD HH24:MI:SS'), 75, 75, 24.00, 18);

INSERT INTO email_campaign (tenant_code, subject, sender_name, sender_email, send_date, total_emails_sent, total_emails_delivered, opened_percent, opened_count)
VALUES ('ASACLUB', 'ASAclub & bluefit - Pesquisa de interesse', 'ASAClub', 'naoresponder@asaclub.org.br', TO_TIMESTAMP('2025-06-16 15:24:02', 'YYYY-MM-DD HH24:MI:SS'), 53, 53, 5.66, 3);

INSERT INTO email_campaign (tenant_code, subject, sender_name, sender_email, send_date, total_emails_sent, total_emails_delivered, opened_percent, opened_count)
VALUES ('ASACLUB', 'ASAclub & AMPCON - Sorteio Especial', 'ASAClub', 'naoresponder@asaclub.org.br', TO_TIMESTAMP('2025-06-16 12:46:04', 'YYYY-MM-DD HH24:MI:SS'), 85, 85, 15.29, 13);

INSERT INTO email_campaign (tenant_code, subject, sender_name, sender_email, send_date, total_emails_sent, total_emails_delivered, opened_percent, opened_count)
VALUES ('ASACLUB', 'ASAclub & ASABNB - Sorteio Especial', 'ASAClub', 'naoresponder@asaclub.org.br', TO_TIMESTAMP('2025-06-16 12:46:03', 'YYYY-MM-DD HH24:MI:SS'), 127, 127, 6.30, 8);

INSERT INTO email_campaign (tenant_code, subject, sender_name, sender_email, send_date, total_emails_sent, total_emails_delivered, opened_percent, opened_count)
VALUES ('ASACLUB', '5 vinhos Altano 2021, exclusivamente para os associados da ASCGU', 'ASAClub', 'naoresponder@asaclub.org.br', TO_TIMESTAMP('2025-06-13 09:44:02', 'YYYY-MM-DD HH24:MI:SS'), 75, 75, 26.67, 20);

INSERT INTO email_campaign (tenant_code, subject, sender_name, sender_email, send_date, total_emails_sent, total_emails_delivered, opened_percent, opened_count)
VALUES ('ASACLUB', 'ASAclub & AMPCON - Sorteio Especial', 'ASAClub', 'naoresponder@asaclub.org.br', TO_TIMESTAMP('2025-06-10 12:46:03', 'YYYY-MM-DD HH24:MI:SS'), 84, 84, 17.86, 15);

INSERT INTO email_campaign (tenant_code, subject, sender_name, sender_email, send_date, total_emails_sent, total_emails_delivered, opened_percent, opened_count)
VALUES ('ASACLUB', 'Bem-vindo ao ASAclub – Seus dados de acesso', 'ASAClub', 'naoresponder@asaclub.org.br', TO_TIMESTAMP('2025-06-06 15:05:02', 'YYYY-MM-DD HH24:MI:SS'), 75, 75, 45.33, 34);

INSERT INTO email_campaign (tenant_code, subject, sender_name, sender_email, send_date, total_emails_sent, total_emails_delivered, opened_percent, opened_count)
VALUES ('ASACLUB', 'ASAclub & AMPCON - Sorteio Especial', 'ASAClub', 'naoresponder@asaclub.org.br', TO_TIMESTAMP('2025-06-04 12:31:03', 'YYYY-MM-DD HH24:MI:SS'), 84, 84, 22.62, 19);

INSERT INTO email_campaign (tenant_code, subject, sender_name, sender_email, send_date, total_emails_sent, total_emails_delivered, opened_percent, opened_count)
VALUES ('ASACLUB', 'ASAclub & ASABNB - Sorteio Especial', 'ASAClub', 'naoresponder@asaclub.org.br', TO_TIMESTAMP('2025-06-04 12:31:03', 'YYYY-MM-DD HH24:MI:SS'), 128, 128, 13.28, 17);

INSERT INTO email_campaign (tenant_code, subject, sender_name, sender_email, send_date, total_emails_sent, total_emails_delivered, opened_percent, opened_count)
VALUES ('ASACLUB', 'ASANews 29/05/2025', 'ASAClub', 'naoresponder@asaclub.org.br', TO_TIMESTAMP('2025-06-03 12:14:03', 'YYYY-MM-DD HH24:MI:SS'), 6767, 6761, 9.88, 668);


--
SELECT * FROM email_campaign;

