-- noinspection SqlSignatureForFile

-- DROP TABLE entity CASCADE CONSTRAINTS;
CREATE TABLE entity
(
    id                          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    --
    id_pessoa_old               INTEGER,
    id_endereco_residencial_old INTEGER,
    id_endereco_comercial_old   INTEGER,
    --
    tenant_code                 VARCHAR2(50)        NOT NULL,
    tenant_id                   INTEGER,
    --     etype_code      VARCHAR2(20)        NOT NULL,
    name                        VARCHAR2(100)       NOT NULL,
    surname                     VARCHAR2(100),
    email                       VARCHAR2(100),
    --     email_hash      VARCHAR2(100) GENERATED ALWAYS AS (standard_hash(email || '2025', 'SHA256')) VIRTUAL,
    birth_date                  DATE,
    birth_date_mask             VARCHAR2(10) GENERATED ALWAYS AS (CAST(mask_br_date(birth_date) AS VARCHAR2(10))) VIRTUAL,
    --
    home_uf                     VARCHAR2(2),
    work_uf                     VARCHAR2(2),
    md5_password                VARCHAR2(100),
    --
    br_cpf                      VARCHAR2(20),
    br_cpf_mask                 VARCHAR2(20) GENERATED ALWAYS AS (CAST(mask_br_cpf(br_cpf) AS VARCHAR2(20))) VIRTUAL,
    --     br_cpf_hash     VARCHAR2(100),
    --
    br_cnpj                     VARCHAR2(20),
    br_cnpj_mask                VARCHAR2(20) GENERATED ALWAYS AS (CAST(mask_br_cnpj(br_cnpj) AS VARCHAR2(20))) VIRTUAL,
    --     br_cnpj_hash    VARCHAR2(100), -- GENERATED ALWAYS AS (standard_hash(br_cnpj || '2025', 'SHA256')) VIRTUAL,
    --
    br_mobile                   VARCHAR2(20),
    br_mobile_mask              VARCHAR2(20) GENERATED ALWAYS AS (CAST(mask_br_phone(br_mobile) AS VARCHAR2(20))) VIRTUAL,
    active                      NUMBER(1) DEFAULT 1 NOT NULL,

    --
    --     CONSTRAINT uq_entity_br_cpf UNIQUE (br_cpf),
    --     CONSTRAINT uq_entity_br_cnpj UNIQUE (br_cnpj),
    --     CONSTRAINT uq_entity_email UNIQUE (email),

    --
    CONSTRAINT ck_entity_home_uf CHECK (home_uf IS NULL OR REGEXP_LIKE(home_uf, '^[A-Z]{2}$')),
    CONSTRAINT ck_entity_work_uf CHECK (work_uf IS NULL OR REGEXP_LIKE(work_uf, '^[A-Z]{2}$')),
    CONSTRAINT ck_entity_br_cpf CHECK (br_cpf IS NULL OR REGEXP_LIKE(br_cpf, '^[0-9]{11}$')),
    CONSTRAINT ck_entity_br_cnpj CHECK (br_cnpj IS NULL OR REGEXP_LIKE(br_cnpj, '^[0-9]{14}$'))
);

SELECT * FROM entity;