-- se fizer drop tem que reimportar do asaclub
-- DROP TABLE tenant CASCADE CONSTRAINTS;
CREATE TABLE tenant (
    id                    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_master             INTEGER,
    --
    id_pessoa_empresa_old INTEGER, -- temp_id_pessoa_empresa
    id_config_father_old  INTEGER, -- temp_id_config_father
    --
    code                  VARCHAR2(50)        NOT NULL,
    name                  VARCHAR2(100)       NOT NULL,
    email                 VARCHAR2(100),
    fake_email            VARCHAR2(100),
    logo_url              VARCHAR2(500),
    created_at            TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at            TIMESTAMP,
    active                NUMBER(1) DEFAULT 1 NOT NULL,

    --
    CONSTRAINT uk_tenant_code UNIQUE (code),
    CONSTRAINT uk_tenant_name UNIQUE (name),
    CONSTRAINT uk_tenant_email UNIQUE (email)
);

--
INSERT INTO tenant (code, name, email, fake_email, active)
VALUES ('SINDICATTO', 'Sindicatto', 'contato@sindicatto.com', 'noreply@inatto.com', 1);

INSERT INTO tenant (code, name, email, active)
VALUES ('INATTO', 'Inatto', 'contato@inatto.com', 1);

-- TODO 20250709 colocar no asaclub
UPDATE tenant SET email = 'asa.convenios@asaclub.org.br' WHERE code = 'ASACLUB';
UPDATE tenant SET email = 'adepdf@adepdf.org.br' WHERE code = 'ADEPDF';
UPDATE tenant SET email = 'luiza@adpf.org.br' WHERE code = 'ADPF';
UPDATE tenant SET email = 'ajufer@ajufer.org.br' WHERE code = 'AJUFER';
UPDATE tenant SET email = 'amatra10regiao@gmail.com' WHERE code = 'AMATRA';

--
SELECT * FROM tenant;
SELECT code, code FROM tenant where id_master=14;