ALTER SESSION SET TIME_ZONE = 'America/Sao_Paulo';

ALTER TABLE wksp_sindicatto.content
    ADD (
        slug varchar2(150),
        sort_order number,
        status varchar2(30) DEFAULT 'published'
        );


-- 20260708-1348
ALTER TABLE wksp_sindicatto.content
    ADD (
        author_name varchar2(300),
        source_name varchar2(300),
        source_url varchar2(1000)
        );

-- 20260708-1348
CREATE TABLE wksp_sindicatto.content_attachment
(
    id              number GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    content_id      number NOT NULL,
    sort_order      number    DEFAULT 0 NOT NULL,
    title           varchar2(500) NOT NULL,
    file_url        varchar2(2000) NOT NULL,
    file_name       varchar2(500),
    mime_type       varchar2(200),
    file_size_bytes number,
    is_external     char(1)   DEFAULT 'Y' CHECK (is_external IN ('Y', 'N')),
    created_at      timestamp DEFAULT systimestamp NOT NULL,
    updated_at      timestamp DEFAULT systimestamp NOT NULL,
    CONSTRAINT fk_content_attachment_content
        FOREIGN KEY (content_id)
            REFERENCES wksp_sindicatto.content (id)
                ON DELETE CASCADE
);