DROP TABLE content;
CREATE TABLE content
(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR2(50),
    ctype_code VARCHAR2(50),
    contents CLOB,
    title VARCHAR2(1000),
    created_at DATE,
    updated_at DATE,
    published_at DATE,
    -- image
    image_blob BLOB,
    image_mime_type VARCHAR2(255),
    image_filename VARCHAR2(500),
    image_alt VARCHAR2(500),
    image_url VARCHAR2(2000),
    image_updated_at TIMESTAMP
)
/