DROP TABLE wksp_sindicatto.email_send_log;
CREATE TABLE wksp_sindicatto.email_send_log
(
    id                number(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    email_queue_id    number(19),
    email_campaign_id number(19),
    email             varchar2(255)                     NOT NULL,
    subject           varchar2(500),
    status            varchar2(30) DEFAULT 'attempt'    NOT NULL,
    error             clob,
    created_at        timestamp    DEFAULT systimestamp NOT NULL,

    CONSTRAINT pk_email_send_log
        PRIMARY KEY (id),

    CONSTRAINT ck_email_send_log_status
        CHECK (status IN (
                          'attempt',
                          'sent',
                          'error',
                          'invalid_email'
            ))
);
/

CREATE INDEX wksp_sindicatto.idx_email_send_log_created_at
    ON wksp_sindicatto.email_send_log (created_at);
/

CREATE INDEX wksp_sindicatto.idx_email_send_log_email
    ON wksp_sindicatto.email_send_log (email);
/

CREATE INDEX wksp_sindicatto.idx_email_send_log_email_email
    ON wksp_sindicatto.email_send_log (email_campaign_id, email);
/

CREATE INDEX wksp_sindicatto.idx_email_send_log_queue
    ON wksp_sindicatto.email_send_log (email_queue_id);
/

SELECT * FROM wksp_sindicatto.email_send_log;