DROP TABLE voting;
DROP TABLE voting_question;
DROP TABLE voting_option;
DROP TABLE voting_answer;

CREATE TABLE voting
(
    id          number GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_voting PRIMARY KEY,
    tenant_code varchar2(50) NOT NULL,

    title       varchar2(500) NOT NULL,
    description clob,

    starts_at   timestamp,
    ends_at     timestamp,

    is_active   number(1) DEFAULT 1 NOT NULL,
    created_at  timestamp DEFAULT systimestamp NOT NULL,
    updated_at  timestamp,

    CONSTRAINT fk_voting_tenant FOREIGN KEY (tenant_code) REFERENCES tenant (code),
    CONSTRAINT ck_voting_active CHECK (is_active IN (0, 1))
);


CREATE TABLE voting_question
(
    id             number GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_voting_question PRIMARY KEY,
    voting_id      number NOT NULL,

    question_order number NOT NULL,
    question_text  clob NOT NULL,

    is_active      number(1) DEFAULT 1 NOT NULL,
    created_at     timestamp DEFAULT systimestamp NOT NULL,
    updated_at     timestamp,

    CONSTRAINT fk_voting_question_voting FOREIGN KEY (voting_id) REFERENCES voting (id),
    CONSTRAINT uk_voting_question_order UNIQUE (voting_id, question_order),
    CONSTRAINT uk_voting_question_id_voting UNIQUE (id, voting_id),
    CONSTRAINT ck_voting_question_active CHECK (is_active IN (0, 1))
);


CREATE TABLE voting_option
(
    id                 number GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_voting_option PRIMARY KEY,
    voting_question_id number NOT NULL,

    option_order       number NOT NULL,
    option_text        varchar2(100) NOT NULL,

    is_active          number(1) DEFAULT 1 NOT NULL,
    created_at         timestamp DEFAULT systimestamp NOT NULL,
    updated_at         timestamp,

    CONSTRAINT fk_voting_option_question FOREIGN KEY (voting_question_id) REFERENCES voting_question (id),
    CONSTRAINT uk_voting_option_order UNIQUE (voting_question_id, option_order),
    CONSTRAINT uk_voting_option_id_question UNIQUE (id, voting_question_id),
    CONSTRAINT ck_voting_option_active CHECK (is_active IN (0, 1))
);


CREATE TABLE voting_answer
(
    id                 number GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pk_voting_answer PRIMARY KEY,
    voting_id          number NOT NULL,
    voting_question_id number NOT NULL,
    voting_option_id   number NOT NULL,

    member_id          number NOT NULL,
    entity_id          number,

    answered_at        timestamp DEFAULT systimestamp NOT NULL,
    ip_address         varchar2(45),

    CONSTRAINT fk_voting_answer_voting FOREIGN KEY (voting_id) REFERENCES voting (id),
    CONSTRAINT fk_voting_answer_question FOREIGN KEY (voting_question_id) REFERENCES voting_question (id),
    CONSTRAINT fk_voting_answer_question_voting FOREIGN KEY (voting_question_id, voting_id) REFERENCES voting_question (id, voting_id),
    CONSTRAINT fk_voting_answer_option_question FOREIGN KEY (voting_option_id, voting_question_id) REFERENCES voting_option (id, voting_question_id),
    CONSTRAINT fk_voting_answer_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_voting_answer_entity FOREIGN KEY (entity_id) REFERENCES entity (id),
    CONSTRAINT uk_voting_answer_once UNIQUE (voting_id, voting_question_id, member_id)
);