create table WKSP_SINDICATTO.ENTITY_LOG
(
    ID           NUMBER generated as identity
        constraint PK_ENTITY_BACKUP_ID
            primary key,
    NAME         VARCHAR2(100) not null,
    TYPE         VARCHAR2(20),
    EMAIL        VARCHAR2(100),
    MOBILE_PHONE VARCHAR2(20),
    BIRTH_DATE   DATE,
    RESD_STATE   VARCHAR2(2),
    WORK_STATE   VARCHAR2(2),
    BR_CPF       VARCHAR2(11),
    BR_CNPJ      VARCHAR2(14)
)
/

create table WKSP_SINDICATTO.MUNICIPALITY
(
    ID               NUMBER generated as identity
        primary key,
    COUNTRY_CODE     VARCHAR2(2)   not null,
    SUBDIVISION_CODE VARCHAR2(10)  not null,
    NAME             VARCHAR2(100) not null,
    BR_IBGE_CODE     VARCHAR2(10)
)
/

create table WKSP_SINDICATTO.COUNTRY
(
    CODE VARCHAR2(2)   not null
        primary key,
    NAME VARCHAR2(100) not null
)
/

create table WKSP_SINDICATTO.COUNTRY_UF
(
    COUNTRY_CODE VARCHAR2(2)   not null
        constraint FK_UF_COUNTRY
            references WKSP_SINDICATTO.COUNTRY,
    CODE         VARCHAR2(10)  not null,
    NAME         VARCHAR2(100) not null,
    constraint PK_COUNTRY_UF
        primary key (COUNTRY_CODE, CODE)
)
/

create table WKSP_SINDICATTO.EMAIL_CAMPAIGN_RECIPIENT
(
    ID              NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_113638".nextval generated by default on null as identity
		primary key,
    CAMPAIGN_ID     NUMBER        not null,
    RECIPIENT_EMAIL VARCHAR2(255) not null,
    STATUS          VARCHAR2(50) default 'pendente',
    SENT_AT         TIMESTAMP(6),
    OPENED_AT       TIMESTAMP(6)
)
/

create table WKSP_SINDICATTO.DEPT
(
    DEPTNO NUMBER(2) not null
        primary key,
    DNAME  VARCHAR2(14),
    LOC    VARCHAR2(13)
)
/

create table WKSP_SINDICATTO.TICKET
(
    ID          NUMBER default "WKSP_SINDICATTO"."ISEQ$$_115523".nextval generated by default on null as identity,
    TENANT_CODE VARCHAR2(50) not null,
    TENANT_ID   NUMBER,
    TITLE       VARCHAR2(1000),
    STATUS      VARCHAR2(20),
    OPEN_DATE   DATE,
    DUE_DATE    DATE,
    DONE_DATE   DATE,
    DESCRIPTION CLOB,
    URGENT      NUMBER default 0
)
/

create table WKSP_SINDICATTO.EMAIL_CAMPAIGN
(
    ID                     NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_116291".nextval generated by default on null as identity
		primary key,
    TENANT_CODE            VARCHAR2(50)  not null,
    TENANT_ID              NUMBER,
    SUBJECT                VARCHAR2(500) not null,
    BODY_HTML              CLOB,
    BODY_TEXT              CLOB,
    SENDER_NAME            VARCHAR2(255),
    SENDER_EMAIL           VARCHAR2(255),
    SEND_DATE              TIMESTAMP(6),
    STATUS                 VARCHAR2(20) default 'pendente',
    RECIPIENT_COUNTRY_CODE VARCHAR2(2),
    RECIPIENT_UF_CODE      VARCHAR2(10),
    CREATED_AT             TIMESTAMP(6) default SYSTIMESTAMP,
    UPDATED_AT             TIMESTAMP(6),
    TOTAL_EMAILS_SENT      NUMBER,
    TOTAL_EMAILS_DELIVERED NUMBER,
    OPENED_PERCENT         NUMBER(5, 2),
    OPENED_COUNT           NUMBER,
    SUBJECT_AI             VARCHAR2(500),
    constraint UK_EMAIL_CAMPAIGN_STATS
        unique (SUBJECT, SEND_DATE),
    constraint FK_CAMPAIGN_UF
        foreign key (RECIPIENT_COUNTRY_CODE, RECIPIENT_UF_CODE) references WKSP_SINDICATTO.COUNTRY_UF
)
/

create table WKSP_SINDICATTO.ADDRESS
(
    ID              NUMBER generated by default on null as identity
        primary key,
    TENANT_CODE     VARCHAR2(50) not null,
    TENANT_ID       NUMBER,
    ENTITY_ID       NUMBER,
    ID_ENDERECO_OLD NUMBER,
    ID_PESSOA_OLD   NUMBER,
    TYPE            VARCHAR2(20),
    UF              VARCHAR2(2)
        constraint CK_ADDRESS_UF
            check (uf IS NULL OR REGEXP_LIKE(uf, '^[A-Z]{2}$')),
    STREET          VARCHAR2(255)
)
/

create table WKSP_SINDICATTO.TENANT
(
    ID                    NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_119286".nextval generated by default on null as identity
		primary key,
    ID_PESSOA_EMPRESA_OLD NUMBER,
    ID_CONFIG_FATHER_OLD  NUMBER,
    CODE                  VARCHAR2(50)           not null
        constraint UK_TENANT_CODE
            unique,
    NAME                  VARCHAR2(100)          not null
        constraint UK_TENANT_NAME
            unique,
    EMAIL                 VARCHAR2(100)
        constraint UK_TENANT_EMAIL
            unique,
    FAKE_EMAIL            VARCHAR2(100),
    LOGO_URL              VARCHAR2(500),
    CREATED_AT            TIMESTAMP(6) default SYSTIMESTAMP,
    UPDATED_AT            TIMESTAMP(6),
    ACTIVE                NUMBER(1)    default 1 not null,
    ID_MASTER             NUMBER
)
/

create table WKSP_SINDICATTO.MEMBER
(
    ID                    NUMBER    default "WKSP_SINDICATTO"."ISEQ$$_119450".nextval generated as identity
		primary key,
    ID_MEMBRO_OLD         NUMBER
        unique,
    ID_PESSOA_OLD         NUMBER,
    ID_PESSOA_EMPRESA_OLD NUMBER,
    TENANT_CODE           VARCHAR2(50)              not null,
    TENANT_ID             NUMBER
        constraint FK_MEMBER_TENANT
            references WKSP_SINDICATTO.TENANT,
    ETYPE_CODE            VARCHAR2(20)              not null,
    ENTITY_ID             NUMBER,
    ACTIVE                NUMBER(1) default 1       not null,
    MUST_UPDATE           NUMBER(1) default 1       not null,
    IS_DEV                NUMBER(1) default 0       not null,
    CREATED_AT            DATE      default SYSDATE,
    INTERNAL_TAG          VARCHAR2(100),
    UPDATED_AT            DATE      default SYSDATE not null
)
/

create table WKSP_SINDICATTO.ENTITY
(
    ID                          NUMBER    default "WKSP_SINDICATTO"."ISEQ$$_119454".nextval generated by default on null as identity
		primary key,
    ID_PESSOA_OLD               NUMBER,
    ID_ENDERECO_RESIDENCIAL_OLD NUMBER,
    ID_ENDERECO_COMERCIAL_OLD   NUMBER,
    TENANT_CODE                 VARCHAR2(50)        not null,
    TENANT_ID                   NUMBER,
    NAME                        VARCHAR2(100)       not null,
    SURNAME                     VARCHAR2(100),
    EMAIL                       VARCHAR2(100),
    BIRTH_DATE                  DATE,
    BIRTH_DATE_MASK             as (CAST("WKSP_SINDICATTO"."MASK_BR_DATE"("BIRTH_DATE") AS VARCHAR2(10))),
    HOME_UF                     VARCHAR2(2)
        constraint CK_ENTITY_HOME_UF
            check (home_uf IS NULL OR REGEXP_LIKE(home_uf, '^[A-Z]{2}$')),
    WORK_UF                     VARCHAR2(2)
        constraint CK_ENTITY_WORK_UF
            check (work_uf IS NULL OR REGEXP_LIKE(work_uf, '^[A-Z]{2}$')),
    MD5_PASSWORD                VARCHAR2(100),
    BR_CPF                      VARCHAR2(20)
        constraint CK_ENTITY_BR_CPF
            check (br_cpf IS NULL OR REGEXP_LIKE(br_cpf, '^[0-9]{11}$')),
    BR_CPF_MASK                 as (CAST("WKSP_SINDICATTO"."MASK_BR_CPF"("BR_CPF") AS VARCHAR2(20))),
    BR_CNPJ                     VARCHAR2(20)
        constraint CK_ENTITY_BR_CNPJ
            check (br_cnpj IS NULL OR REGEXP_LIKE(br_cnpj, '^[0-9]{14}$')),
    BR_CNPJ_MASK                as (CAST("WKSP_SINDICATTO"."MASK_BR_CNPJ"("BR_CNPJ") AS VARCHAR2(20))),
    BR_MOBILE                   VARCHAR2(20),
    BR_MOBILE_MASK              as (CAST("WKSP_SINDICATTO"."MASK_BR_PHONE"("BR_MOBILE") AS VARCHAR2(20))),
    ACTIVE                      NUMBER(1) default 1 not null,
    INTERNAL_TAG                VARCHAR2(100)
)
/

create table WKSP_SINDICATTO.MV_PARTNERSHIP_PARTNERS
(
    TENANT_CODE VARCHAR2(50) not null,
    PARENT_CODE VARCHAR2(50) not null,
    ROLE        VARCHAR2(50),
    constraint SYS_C_SNAP$_8PK_PARTNERSHIP
        primary key (TENANT_CODE, PARENT_CODE)
)
/

create table WKSP_SINDICATTO.ETYPE
(
    ID             NUMBER    default "WKSP_SINDICATTO"."ISEQ$$_120702".nextval generated by default on null as identity
		primary key,
    TENANT_CODE    VARCHAR2(50)        not null,
    CODE           VARCHAR2(100),
    ID_PERFIL_OLD  NUMBER,
    TAG_PERFIL_OLD VARCHAR2(100),
    NAME           VARCHAR2(50)        not null,
    PLURAL_NAME    VARCHAR2(50)        not null,
    DESCRIPTION    VARCHAR2(200),
    READ_ONLY      NUMBER(1) default 1 not null,
    IS_ADMIN       NUMBER(1) default 1 not null,
    ACTIVE         NUMBER(1) default 1 not null,
    HASH           as (ORA_HASH("CODE")),
    constraint UK_ETYPE_TENANT_CODE
        unique (TENANT_CODE, CODE)
)
/

create table WKSP_SINDICATTO.ROLE_ETYPE
(
    ROLE_CODE  VARCHAR2(50) not null,
    ETYPE_CODE VARCHAR2(20) not null,
    constraint PK_ROLE_ETYPE
        primary key (ROLE_CODE, ETYPE_CODE)
)
/

create table WKSP_SINDICATTO.PARTNERSHIP
(
    TENANT_CODE VARCHAR2(50) not null
        constraint FK_PARTNERSHIP_TENANT
            references WKSP_SINDICATTO.TENANT (CODE),
    PARENT_CODE VARCHAR2(50) not null
        constraint FK_PARTNERSHIP_PARENT
            references WKSP_SINDICATTO.TENANT (CODE),
    ROLE        VARCHAR2(50)
        check (role IN ('partner', 'client')),
    constraint PK_PARTNERSHIP
        primary key (TENANT_CODE, PARENT_CODE),
    constraint CHK_PARTNERSHIP_NOT_SELF
        check (tenant_code != parent_code)
)
/

create table WKSP_SINDICATTO.DBTOOLS$EXECUTION_HISTORY
(
    ID         NUMBER not null
        constraint DBTOOLS$EXECUTION_HISTORY_PK
            primary key,
    HASH       CLOB,
    CREATED_BY VARCHAR2(255),
    CREATED_ON TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY VARCHAR2(255),
    UPDATED_ON TIMESTAMP(6) WITH TIME ZONE,
    STATEMENT  CLOB,
    TIMES      NUMBER
)
/

create table WKSP_SINDICATTO.TENANT_PERMISSION
(
    ID          NUMBER generated as identity
        primary key,
    TENANT_CODE VARCHAR2(50)  not null,
    PAGE_ALIAS  VARCHAR2(100) not null,
    constraint UK_TENANT_PERMISSION_TENANT_PAGE
        unique (TENANT_CODE, PAGE_ALIAS)
)
/

create table WKSP_SINDICATTO.PROCESSO_BR
(
    ID                              NUMBER default "WKSP_SINDICATTO"."ISEQ$$_124740".nextval generated by default on null as identity
		primary key,
    TENANT_CODE                     VARCHAR2(50),
    NOME                            VARCHAR2(500),
    CPF                             VARCHAR2(100),
    CPF_MASK                        as (CAST("WKSP_SINDICATTO"."MASK_BR_CPF"("CPF") AS VARCHAR2(20))),
    SITUACAO_FUNCIONAL              VARCHAR2(100),
    NOME_PENSIONISTA                VARCHAR2(150),
    CPF_PENSIONISTA                 VARCHAR2(100),
    CPF_PENSIONISTA_MASK            as (CAST("WKSP_SINDICATTO"."MASK_BR_CPF"("CPF_PENSIONISTA") AS VARCHAR2(20))),
    AUTOR_ACAO                      VARCHAR2(150),
    OBJETO_ACAO                     VARCHAR2(200),
    ESCRITORIO_RESPONSAVEL          VARCHAR2(150),
    PARTE_CONTRARIA                 VARCHAR2(150),
    NR_PROCESSO                     VARCHAR2(100),
    VARA_PROCESSO                   VARCHAR2(150),
    NR_CUMPRIMENTO                  VARCHAR2(100),
    NR_EMBARGOS                     VARCHAR2(100),
    VARA_CUMPRIMENTO                VARCHAR2(150),
    VALOR_EXECUTADO                 VARCHAR2(100),
    VALOR_ACAO                      VARCHAR2(100),
    VALOR_ACORDO_AGU                VARCHAR2(100),
    NR_PRECATORIO                   VARCHAR2(100),
    VALOR_PRECATORIO                VARCHAR2(100),
    DATA_EXPEDICAO_PRECATORIO       DATE,
    DATA_EXPEDICAO_PRECATORIO_MASK  as (CAST("WKSP_SINDICATTO"."MASK_BR_DATE"("DATA_EXPEDICAO_PRECATORIO") AS VARCHAR2(10))),
    NR_SUPLEMENTAR                  VARCHAR2(150),
    VALOR_SUPLEMENTAR               VARCHAR2(100),
    DATA_EXPEDICAO_SUPLEMENTAR      DATE,
    DATA_EXPEDICAO_SUPLEMENTAR_MASK as (CAST("WKSP_SINDICATTO"."MASK_BR_DATE"("DATA_EXPEDICAO_SUPLEMENTAR") AS VARCHAR2(10))),
    VALOR_DEVOLVIDO                 VARCHAR2(100),
    DATA_DEVOLUCAO                  DATE,
    DATA_DEVOLUCAO_MASK             as (CAST("WKSP_SINDICATTO"."MASK_BR_DATE"("DATA_DEVOLUCAO") AS VARCHAR2(10))),
    ULTIMO_ANDMENTO                 VARCHAR2(1000),
    SITUACAO_PAGAMENTO              VARCHAR2(100),
    SITUACAO_CUMPRIMENTO_SENTENCA   VARCHAR2(200),
    SITUACAO_EMBARGOS_EXECUCAO      VARCHAR2(200)
)
/

create table WKSP_SINDICATTO.SENDER
(
    EMAIL                      VARCHAR2(255),
    GROUPS                     VARCHAR2(500),
    PHONE                      VARCHAR2(50),
    EMAIL_STATUS               VARCHAR2(50),
    SMS_STATUS                 VARCHAR2(50),
    TRANSACTIONAL_EMAIL_STATUS VARCHAR2(50),
    TRANSACTIONAL_SMS_STATUS   VARCHAR2(50),
    LOCATION                   VARCHAR2(255),
    CREATED                    DATE,
    LAST_NAME                  VARCHAR2(255),
    FIRST_NAME                 VARCHAR2(255),
    IDADE                      NUMBER,
    SENHA                      VARCHAR2(255),
    ENTIDADE                   VARCHAR2(255),
    UF                         VARCHAR2(2),
    ID_MEMBRO                  NUMBER,
    DATA_NASCIMENTO            DATE,
    ID_PESSOA                  NUMBER,
    CPF                        VARCHAR2(14)
)
/

create table WKSP_SINDICATTO.LOGIN_LOG
(
    ID          NUMBER default "WKSP_SINDICATTO"."ISEQ$$_125393".nextval generated by default on null as identity
		primary key,
    MEMBER_ID   NUMBER,
    ENTITY_ID   NUMBER,
    LOGIN_USER  VARCHAR2(255),
    TENANT_CODE VARCHAR2(100),
    ETYPE_CODE  VARCHAR2(50),
    SUCCESS     NUMBER(1),
    ERROR_CODE  VARCHAR2(20),
    IP_ADDRESS  VARCHAR2(45),
    SQL_ERROR   VARCHAR2(4000),
    USER_AGENT  VARCHAR2(4000),
    CREATED_AT  DATE   default SYSDATE
)
/

create table WKSP_SINDICATTO.SMTP2GO
(
    ID               NUMBER generated by default on null as identity
        primary key,
    EMAIL_ID         VARCHAR2(50),
    EVENT_DATE       TIMESTAMP(9) WITH TIME ZONE,
    EVENT_TYPE       VARCHAR2(50),
    USERNAME         VARCHAR2(100),
    FROM_EMAIL       VARCHAR2(50),
    REPLY_TO         VARCHAR2(32767),
    RECIPIENT        VARCHAR2(255),
    SUBJECT          VARCHAR2(255),
    REASON           VARCHAR2(32767),
    SIZE_BYTES       NUMBER,
    ORIGINATING_HOST VARCHAR2(255),
    OUTBOUND_IP      VARCHAR2(50),
    EMAIL_CLIENT     VARCHAR2(255),
    USER_AGENT       VARCHAR2(32767),
    SUBMITTED        TIMESTAMP(9) WITH TIME ZONE
)
/

create unique index WKSP_SINDICATTO.UK_SMTP2GO_EVENT
    on WKSP_SINDICATTO.SMTP2GO (EMAIL_ID, SYS_EXTRACT_UTC("EVENT_DATE"), EVENT_TYPE, RECIPIENT)
/

create table WKSP_SINDICATTO.THIRD_DIA_DIA
(
    ID                NUMBER generated as identity
        primary key,
    CODIGO_GRUPO      NUMBER,
    ORIGEM            VARCHAR2(100),
    CPF               VARCHAR2(11) not null
        constraint UK_CPF
            unique,
    ID_DESCONHECIDO   NUMBER,
    NOME              VARCHAR2(100),
    STATUS_GERAL      CHAR,
    DATA_GERAL        DATE,
    STATUS_BIOMETRIA  VARCHAR2(20),
    STATUS_ASSOCIACAO VARCHAR2(100)
)
/

create table WKSP_SINDICATTO.CONVENIO
(
    ID               NUMBER(10) generated as identity
        primary key,
    TITULO           VARCHAR2(255),
    HTML_REGULAMENTO CLOB,
    HTML_ASSOCIADO   CLOB,
    ACTIVE           NUMBER(1)
)
/

create table WKSP_SINDICATTO.CONTENT
(
    ID               NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_210720".nextval generated as identity
		primary key,
    TENANT_CODE      VARCHAR2(50),
    CTYPE_CODE       VARCHAR2(50),
    CONTENTS         CLOB,
    TITLE            VARCHAR2(1000),
    CREATED_AT       DATE,
    UPDATED_AT       DATE,
    PUBLISHED_AT     DATE,
    IMAGE_BLOB       BLOB,
    IMAGE_MIME_TYPE  VARCHAR2(255),
    IMAGE_FILENAME   VARCHAR2(500),
    IMAGE_ALT        VARCHAR2(500),
    IMAGE_URL        VARCHAR2(2000),
    IMAGE_UPDATED_AT TIMESTAMP(6),
    CONTENT_FORMAT   VARCHAR2(100),
    SLUG             VARCHAR2(150),
    SORT_ORDER       NUMBER,
    STATUS           VARCHAR2(30) default 'published'
)
/

create unique index WKSP_SINDICATTO.IDX_CONTENT_TENANT_CTYPE_SLUG
    on WKSP_SINDICATTO.CONTENT (CASE WHEN TRIM("SLUG") IS NOT NULL THEN LOWER("TENANT_CODE") END,
                                CASE WHEN TRIM("SLUG") IS NOT NULL THEN LOWER("CTYPE_CODE") END,
                                CASE WHEN TRIM("SLUG") IS NOT NULL THEN LOWER(TRIM("SLUG")) END)
/

create table WKSP_SINDICATTO.EMAIL_BLACKLIST
(
    ID         NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_214466".nextval generated by default on null as identity
		constraint PK_EMAIL_BLACKLIST
			primary key,
    EMAIL      VARCHAR2(255)
        constraint UQ_EMAIL_BLACKLIST_EMAIL
            unique,
    REASON     CLOB,
    CREATED_AT TIMESTAMP(6) default current_timestamp
)
/

create table WKSP_SINDICATTO.EMAIL_QUEUE
(
    ID                 NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_214477".nextval generated as identity
		constraint EMAIL_QUEUE_PK
			primary key,
    EMAIL_CAMPAIGN_ID  NUMBER
        constraint EMAIL_QUEUE_CAMPAIGN_FK
            references WKSP_SINDICATTO.EMAIL_CAMPAIGN,
    MEMBER_ID          NUMBER,
    MEMBER_INSERT_DATE DATE,
    PERSON_ID          NUMBER,
    EMAIL              VARCHAR2(255) not null,
    STATUS             VARCHAR2(20) default 'pending'
        constraint EMAIL_QUEUE_STATUS_CK
            check (status IN ('pending', 'sent', 'error', 'invalid_email', 'processing')),
    LAST_TRY           DATE,
    OPENED_AT          DATE,
    NAME               VARCHAR2(255),
    COMPANY            VARCHAR2(100),
    HOME_UF            CHAR(2),
    WORK_UF            CHAR(2),
    BLOCKED            NUMBER(1)    default 0
        constraint EMAIL_QUEUE_BLOCKED_CK
            check (blocked IN (0, 1)),
    PRIORITY           NUMBER       default 10,
    ERROR              CLOB,
    CREATED_AT         DATE         default SYSDATE
)
/

create index WKSP_SINDICATTO.EMAIL_QUEUE_EMAIL_IDX
    on WKSP_SINDICATTO.EMAIL_QUEUE (EMAIL)
/

create index WKSP_SINDICATTO.EMAIL_QUEUE_MEMBER_INSERT_DATE_IDX
    on WKSP_SINDICATTO.EMAIL_QUEUE (MEMBER_INSERT_DATE)
/

create index WKSP_SINDICATTO.EMAIL_QUEUE_STATUS_IDX
    on WKSP_SINDICATTO.EMAIL_QUEUE (STATUS)
/

create index WKSP_SINDICATTO.EMAIL_QUEUE_CAMPAIGN_IDX
    on WKSP_SINDICATTO.EMAIL_QUEUE (EMAIL_CAMPAIGN_ID)
/

create table WKSP_SINDICATTO.EMAIL_SEND_LOG
(
    ID                NUMBER(19)   default "WKSP_SINDICATTO"."ISEQ$$_214532".nextval generated by default on null as identity
		constraint PK_EMAIL_SEND_LOG
			primary key,
    EMAIL_QUEUE_ID    NUMBER(19),
    EMAIL_CAMPAIGN_ID NUMBER(19),
    EMAIL             VARCHAR2(255)                     not null,
    SUBJECT           VARCHAR2(500),
    STATUS            VARCHAR2(30) default 'attempt'    not null
        constraint CK_EMAIL_SEND_LOG_STATUS
            check (status IN (
                              'attempt',
                              'sent',
                              'error',
                              'invalid_email'
                )),
    ERROR             CLOB,
    CREATED_AT        TIMESTAMP(6) default systimestamp not null
)
/

create index WKSP_SINDICATTO.IDX_EMAIL_SEND_LOG_CREATED_AT
    on WKSP_SINDICATTO.EMAIL_SEND_LOG (CREATED_AT)
/

create index WKSP_SINDICATTO.IDX_EMAIL_SEND_LOG_EMAIL
    on WKSP_SINDICATTO.EMAIL_SEND_LOG (EMAIL)
/

create index WKSP_SINDICATTO.IDX_EMAIL_SEND_LOG_EMAIL_EMAIL
    on WKSP_SINDICATTO.EMAIL_SEND_LOG (EMAIL_CAMPAIGN_ID, EMAIL)
/

create index WKSP_SINDICATTO.IDX_EMAIL_SEND_LOG_QUEUE
    on WKSP_SINDICATTO.EMAIL_SEND_LOG (EMAIL_QUEUE_ID)
/

create table WKSP_SINDICATTO.CTYPE
(
    ID             NUMBER    default "WKSP_SINDICATTO"."ISEQ$$_214557".nextval generated by default on null as identity
		primary key,
    TENANT_CODE    VARCHAR2(50)        not null,
    CODE           VARCHAR2(100),
    ID_PERFIL_OLD  NUMBER,
    TAG_PERFIL_OLD VARCHAR2(100),
    NAME           VARCHAR2(50)        not null,
    PLURAL_NAME    VARCHAR2(50)        not null,
    DESCRIPTION    VARCHAR2(200),
    READ_ONLY      NUMBER(1) default 1 not null,
    IS_ADMIN       NUMBER(1) default 1 not null,
    ACTIVE         NUMBER(1) default 1 not null,
    HASH           as (ORA_HASH("CODE")),
    constraint UK_CTYPE_TENANT_CODE
        unique (TENANT_CODE, CODE)
)
/

create table WKSP_SINDICATTO.ETYPE_PERMISSION
(
    ID           NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_216505".nextval generated as identity
		primary key,
    TENANT_CODE  VARCHAR2(50)                      not null,
    ETYPE_CODE   VARCHAR2(50)                      not null,
    PAGE_ALIAS   VARCHAR2(100)                     not null,
    ACTION_CODE  VARCHAR2(50)                      not null,
    REQUIRES_DEV NUMBER(1)    default 0            not null
        constraint CK_ETYPE_PERMISSION_REQUIRES_DEV
            check (requires_dev IN (0, 1)),
    ACTIVE       NUMBER(1)    default 1            not null
        check (active IN (0, 1)),
    CREATED_AT   TIMESTAMP(6) default systimestamp not null,
    constraint UQ_ETYPE_PERMISSION
        unique (TENANT_CODE, ETYPE_CODE, PAGE_ALIAS, ACTION_CODE, REQUIRES_DEV),
    constraint FK_ETYPE_PERMISSION_ETYPE
        foreign key (TENANT_CODE, ETYPE_CODE) references WKSP_SINDICATTO.ETYPE (TENANT_CODE, CODE),
    constraint FK_ETYPE_PERMISSION_TENANT_PERMISSION
        foreign key (TENANT_CODE, PAGE_ALIAS) references WKSP_SINDICATTO.TENANT_PERMISSION (TENANT_CODE, PAGE_ALIAS)
)
/

