create sequence EMP_SEQ
/

create sequence DEPT_SEQ
/

create sequence DBTOOLS$EXECUTION_HISTORY_SEQ
/

create table ENTITY_LOG
(
    ID           NUMBER generated as identity
        constraint PK_ENTITY_BACKUP_ID
            primary key,
    NAME         VARCHAR2(100) not null,
    TYPE         VARCHAR2(20),
    EMAIL        VARCHAR2(100),
    MOBILE_PHONE VARCHAR2(20),
    BIRTH_DATE   DATE,
    RESD_STATE   VARCHAR2(2),
    WORK_STATE   VARCHAR2(2),
    BR_CPF       VARCHAR2(11),
    BR_CNPJ      VARCHAR2(14)
)
/

create table MUNICIPALITY
(
    ID               NUMBER generated as identity
        primary key,
    COUNTRY_CODE     VARCHAR2(2)   not null,
    SUBDIVISION_CODE VARCHAR2(10)  not null,
    NAME             VARCHAR2(100) not null,
    BR_IBGE_CODE     VARCHAR2(10)
)
/

create table COUNTRY
(
    CODE VARCHAR2(2)   not null
        primary key,
    NAME VARCHAR2(100) not null
)
/

create table COUNTRY_UF
(
    COUNTRY_CODE VARCHAR2(2)   not null
        constraint FK_UF_COUNTRY
            references COUNTRY,
    CODE         VARCHAR2(10)  not null,
    NAME         VARCHAR2(100) not null,
    constraint PK_COUNTRY_UF
        primary key (COUNTRY_CODE, CODE)
)
/

create table EMAIL_CAMPAIGN_RECIPIENT
(
    ID              NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_113638".nextval generated by default on null as identity
		primary key,
    CAMPAIGN_ID     NUMBER        not null,
    RECIPIENT_EMAIL VARCHAR2(255) not null,
    STATUS          VARCHAR2(50) default 'pendente',
    SENT_AT         TIMESTAMP(6),
    OPENED_AT       TIMESTAMP(6)
)
/

create table DEPT
(
    DEPTNO NUMBER(2) not null
        primary key,
    DNAME  VARCHAR2(14),
    LOC    VARCHAR2(13)
)
/

create table "--EMP"
(
    EMPNO    NUMBER(4) not null
        primary key,
    ENAME    VARCHAR2(10),
    JOB      VARCHAR2(9),
    MGR      NUMBER(4)
        references "--EMP",
    HIREDATE DATE,
    SAL      NUMBER(7, 2),
    COMM     NUMBER(7, 2),
    DEPTNO   NUMBER(2)
        references DEPT
)
/

create table TICKET
(
    ID          NUMBER default "WKSP_SINDICATTO"."ISEQ$$_115523".nextval generated by default on null as identity,
    TENANT_CODE VARCHAR2(50) not null,
    TENANT_ID   NUMBER,
    TITLE       VARCHAR2(1000),
    STATUS      VARCHAR2(20),
    OPEN_DATE   DATE,
    DUE_DATE    DATE,
    DONE_DATE   DATE,
    DESCRIPTION CLOB,
    URGENT      NUMBER default 0
)
/

create table EMAIL_CAMPAIGN
(
    ID                     NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_116291".nextval generated by default on null as identity
		primary key,
    TENANT_CODE            VARCHAR2(50)  not null,
    TENANT_ID              NUMBER,
    SUBJECT                VARCHAR2(500) not null,
    BODY_HTML              CLOB,
    BODY_TEXT              CLOB,
    SENDER_NAME            VARCHAR2(255),
    SENDER_EMAIL           VARCHAR2(255),
    SEND_DATE              TIMESTAMP(6),
    STATUS                 VARCHAR2(20) default 'pendente',
    RECIPIENT_COUNTRY_CODE VARCHAR2(2),
    RECIPIENT_UF_CODE      VARCHAR2(10),
    CREATED_AT             TIMESTAMP(6) default SYSTIMESTAMP,
    UPDATED_AT             TIMESTAMP(6),
    TOTAL_EMAILS_SENT      NUMBER,
    TOTAL_EMAILS_DELIVERED NUMBER,
    OPENED_PERCENT         NUMBER(5, 2),
    OPENED_COUNT           NUMBER,
    SUBJECT_AI             VARCHAR2(500),
    constraint UK_EMAIL_CAMPAIGN_STATS
        unique (SUBJECT, SEND_DATE),
    constraint FK_CAMPAIGN_UF
        foreign key (RECIPIENT_COUNTRY_CODE, RECIPIENT_UF_CODE) references COUNTRY_UF
)
/

create table ADDRESS
(
    ID              NUMBER generated by default on null as identity
        primary key,
    TENANT_CODE     VARCHAR2(50) not null,
    TENANT_ID       NUMBER,
    ENTITY_ID       NUMBER,
    ID_ENDERECO_OLD NUMBER,
    ID_PESSOA_OLD   NUMBER,
    TYPE            VARCHAR2(20),
    UF              VARCHAR2(2)
        constraint CK_ADDRESS_UF
            check (uf IS NULL OR REGEXP_LIKE(uf, '^[A-Z]{2}$')),
    STREET          VARCHAR2(255)
)
/

create table TENANT
(
    ID                    NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_119286".nextval generated by default on null as identity
		primary key,
    ID_PESSOA_EMPRESA_OLD NUMBER,
    ID_CONFIG_FATHER_OLD  NUMBER,
    CODE                  VARCHAR2(50)           not null
        constraint UK_TENANT_CODE
            unique,
    NAME                  VARCHAR2(100)          not null
        constraint UK_TENANT_NAME
            unique,
    EMAIL                 VARCHAR2(100)
        constraint UK_TENANT_EMAIL
            unique,
    FAKE_EMAIL            VARCHAR2(100),
    LOGO_URL              VARCHAR2(500),
    CREATED_AT            TIMESTAMP(6) default SYSTIMESTAMP,
    UPDATED_AT            TIMESTAMP(6),
    ACTIVE                NUMBER(1)    default 1 not null,
    ID_MASTER             NUMBER,
    DESCRIPTION           VARCHAR2(100)
)
/

create table MEMBER
(
    ID                    NUMBER    default "WKSP_SINDICATTO"."ISEQ$$_119450".nextval generated as identity
		primary key,
    ID_MEMBRO_OLD         NUMBER
        unique,
    ID_PESSOA_OLD         NUMBER,
    ID_PESSOA_EMPRESA_OLD NUMBER,
    TENANT_CODE           VARCHAR2(50)              not null,
    TENANT_ID             NUMBER
        constraint FK_MEMBER_TENANT
            references TENANT,
    ETYPE_CODE            VARCHAR2(20)              not null,
    ENTITY_ID             NUMBER,
    ACTIVE                NUMBER(1) default 1       not null,
    MUST_UPDATE           NUMBER(1) default 1       not null,
    IS_DEV                NUMBER(1) default 0       not null,
    CREATED_AT            DATE      default SYSDATE,
    INTERNAL_TAG          VARCHAR2(100),
    UPDATED_AT            DATE      default SYSDATE not null
)
/

create table ENTITY
(
    ID                          NUMBER    default "WKSP_SINDICATTO"."ISEQ$$_119454".nextval generated by default on null as identity
		primary key,
    ID_PESSOA_OLD               NUMBER,
    ID_ENDERECO_RESIDENCIAL_OLD NUMBER,
    ID_ENDERECO_COMERCIAL_OLD   NUMBER,
    TENANT_CODE                 VARCHAR2(50)        not null,
    TENANT_ID                   NUMBER,
    NAME                        VARCHAR2(100)       not null,
    SURNAME                     VARCHAR2(100),
    EMAIL                       VARCHAR2(100),
    BIRTH_DATE                  DATE,
    BIRTH_DATE_MASK             as (CAST("WKSP_SINDICATTO"."MASK_BR_DATE"("BIRTH_DATE") AS VARCHAR2(10))),
    HOME_UF                     VARCHAR2(2)
        constraint CK_ENTITY_HOME_UF
            check (home_uf IS NULL OR REGEXP_LIKE(home_uf, '^[A-Z]{2}$')),
    WORK_UF                     VARCHAR2(2)
        constraint CK_ENTITY_WORK_UF
            check (work_uf IS NULL OR REGEXP_LIKE(work_uf, '^[A-Z]{2}$')),
    MD5_PASSWORD                VARCHAR2(100),
    BR_CPF                      VARCHAR2(20)
        constraint CK_ENTITY_BR_CPF
            check (br_cpf IS NULL OR REGEXP_LIKE(br_cpf, '^[0-9]{11}$')),
    BR_CPF_MASK                 as (CAST("WKSP_SINDICATTO"."MASK_BR_CPF"("BR_CPF") AS VARCHAR2(20))),
    BR_CNPJ                     VARCHAR2(20)
        constraint CK_ENTITY_BR_CNPJ
            check (br_cnpj IS NULL OR REGEXP_LIKE(br_cnpj, '^[0-9]{14}$')),
    BR_CNPJ_MASK                as (CAST("WKSP_SINDICATTO"."MASK_BR_CNPJ"("BR_CNPJ") AS VARCHAR2(20))),
    BR_MOBILE                   VARCHAR2(20),
    BR_MOBILE_MASK              as (CAST("WKSP_SINDICATTO"."MASK_BR_PHONE"("BR_MOBILE") AS VARCHAR2(20))),
    ACTIVE                      NUMBER(1) default 1 not null,
    INTERNAL_TAG                VARCHAR2(100)
)
/

create table ETYPE
(
    ID             NUMBER    default "WKSP_SINDICATTO"."ISEQ$$_120702".nextval generated by default on null as identity
		primary key,
    TENANT_CODE    VARCHAR2(50)        not null,
    CODE           VARCHAR2(100),
    ID_PERFIL_OLD  NUMBER,
    TAG_PERFIL_OLD VARCHAR2(100),
    NAME           VARCHAR2(50)        not null,
    PLURAL_NAME    VARCHAR2(50)        not null,
    DESCRIPTION    VARCHAR2(200),
    READ_ONLY      NUMBER(1) default 1 not null,
    IS_ADMIN       NUMBER(1) default 1 not null,
    ACTIVE         NUMBER(1) default 1 not null,
    HASH           as (ORA_HASH("CODE")),
    constraint UK_ETYPE_TENANT_CODE
        unique (TENANT_CODE, CODE)
)
/

create table ROLE_ETYPE
(
    ROLE_CODE  VARCHAR2(50) not null,
    ETYPE_CODE VARCHAR2(20) not null,
    constraint PK_ROLE_ETYPE
        primary key (ROLE_CODE, ETYPE_CODE)
)
/

create table PARTNERSHIP
(
    TENANT_CODE VARCHAR2(50) not null
        constraint FK_PARTNERSHIP_TENANT
            references TENANT (CODE),
    PARENT_CODE VARCHAR2(50) not null
        constraint FK_PARTNERSHIP_PARENT
            references TENANT (CODE),
    ROLE        VARCHAR2(50)
        check (role IN ('partner', 'client')),
    constraint PK_PARTNERSHIP
        primary key (TENANT_CODE, PARENT_CODE),
    constraint CHK_PARTNERSHIP_NOT_SELF
        check (tenant_code != parent_code)
)
/

create table DBTOOLS$EXECUTION_HISTORY
(
    ID         NUMBER not null
        constraint DBTOOLS$EXECUTION_HISTORY_PK
            primary key,
    HASH       CLOB,
    CREATED_BY VARCHAR2(255),
    CREATED_ON TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY VARCHAR2(255),
    UPDATED_ON TIMESTAMP(6) WITH TIME ZONE,
    STATEMENT  CLOB,
    TIMES      NUMBER
)
/

create table TENANT_PERMISSION
(
    ID          NUMBER generated as identity
        primary key,
    TENANT_CODE VARCHAR2(50)  not null,
    PAGE_ALIAS  VARCHAR2(100) not null,
    constraint UK_TENANT_PERMISSION_TENANT_PAGE
        unique (TENANT_CODE, PAGE_ALIAS)
)
/

create table PROCESSO_BR
(
    ID                              NUMBER default "WKSP_SINDICATTO"."ISEQ$$_124740".nextval generated by default on null as identity
		primary key,
    TENANT_CODE                     VARCHAR2(50),
    NOME                            VARCHAR2(500),
    CPF                             VARCHAR2(100),
    CPF_MASK                        as (CAST("WKSP_SINDICATTO"."MASK_BR_CPF"("CPF") AS VARCHAR2(20))),
    SITUACAO_FUNCIONAL              VARCHAR2(100),
    NOME_PENSIONISTA                VARCHAR2(150),
    CPF_PENSIONISTA                 VARCHAR2(100),
    CPF_PENSIONISTA_MASK            as (CAST("WKSP_SINDICATTO"."MASK_BR_CPF"("CPF_PENSIONISTA") AS VARCHAR2(20))),
    AUTOR_ACAO                      VARCHAR2(150),
    OBJETO_ACAO                     VARCHAR2(200),
    ESCRITORIO_RESPONSAVEL          VARCHAR2(150),
    PARTE_CONTRARIA                 VARCHAR2(150),
    NR_PROCESSO                     VARCHAR2(100),
    VARA_PROCESSO                   VARCHAR2(150),
    NR_CUMPRIMENTO                  VARCHAR2(100),
    NR_EMBARGOS                     VARCHAR2(100),
    VARA_CUMPRIMENTO                VARCHAR2(150),
    VALOR_EXECUTADO                 VARCHAR2(100),
    VALOR_ACAO                      VARCHAR2(100),
    VALOR_ACORDO_AGU                VARCHAR2(100),
    NR_PRECATORIO                   VARCHAR2(100),
    VALOR_PRECATORIO                VARCHAR2(100),
    DATA_EXPEDICAO_PRECATORIO       DATE,
    DATA_EXPEDICAO_PRECATORIO_MASK  as (CAST("WKSP_SINDICATTO"."MASK_BR_DATE"("DATA_EXPEDICAO_PRECATORIO") AS VARCHAR2(10))),
    NR_SUPLEMENTAR                  VARCHAR2(150),
    VALOR_SUPLEMENTAR               VARCHAR2(100),
    DATA_EXPEDICAO_SUPLEMENTAR      DATE,
    DATA_EXPEDICAO_SUPLEMENTAR_MASK as (CAST("WKSP_SINDICATTO"."MASK_BR_DATE"("DATA_EXPEDICAO_SUPLEMENTAR") AS VARCHAR2(10))),
    VALOR_DEVOLVIDO                 VARCHAR2(100),
    DATA_DEVOLUCAO                  DATE,
    DATA_DEVOLUCAO_MASK             as (CAST("WKSP_SINDICATTO"."MASK_BR_DATE"("DATA_DEVOLUCAO") AS VARCHAR2(10))),
    ULTIMO_ANDMENTO                 VARCHAR2(1000),
    SITUACAO_PAGAMENTO              VARCHAR2(100),
    SITUACAO_CUMPRIMENTO_SENTENCA   VARCHAR2(200),
    SITUACAO_EMBARGOS_EXECUCAO      VARCHAR2(200)
)
/

create table SENDER
(
    EMAIL                      VARCHAR2(255),
    GROUPS                     VARCHAR2(500),
    PHONE                      VARCHAR2(50),
    EMAIL_STATUS               VARCHAR2(50),
    SMS_STATUS                 VARCHAR2(50),
    TRANSACTIONAL_EMAIL_STATUS VARCHAR2(50),
    TRANSACTIONAL_SMS_STATUS   VARCHAR2(50),
    LOCATION                   VARCHAR2(255),
    CREATED                    DATE,
    LAST_NAME                  VARCHAR2(255),
    FIRST_NAME                 VARCHAR2(255),
    IDADE                      NUMBER,
    SENHA                      VARCHAR2(255),
    ENTIDADE                   VARCHAR2(255),
    UF                         VARCHAR2(2),
    ID_MEMBRO                  NUMBER,
    DATA_NASCIMENTO            DATE,
    ID_PESSOA                  NUMBER,
    CPF                        VARCHAR2(14)
)
/

create table LOGIN_LOG
(
    ID          NUMBER default "WKSP_SINDICATTO"."ISEQ$$_125393".nextval generated by default on null as identity
		primary key,
    MEMBER_ID   NUMBER,
    ENTITY_ID   NUMBER,
    LOGIN_USER  VARCHAR2(255),
    TENANT_CODE VARCHAR2(100),
    ETYPE_CODE  VARCHAR2(50),
    SUCCESS     NUMBER(1),
    ERROR_CODE  VARCHAR2(20),
    IP_ADDRESS  VARCHAR2(45),
    SQL_ERROR   VARCHAR2(4000),
    USER_AGENT  VARCHAR2(4000),
    CREATED_AT  DATE   default SYSDATE
)
/

create table SMTP2GO
(
    ID               NUMBER generated by default on null as identity
        primary key,
    EMAIL_ID         VARCHAR2(50),
    EVENT_DATE       TIMESTAMP(9) WITH TIME ZONE,
    EVENT_TYPE       VARCHAR2(50),
    USERNAME         VARCHAR2(100),
    FROM_EMAIL       VARCHAR2(50),
    REPLY_TO         VARCHAR2(32767),
    RECIPIENT        VARCHAR2(255),
    SUBJECT          VARCHAR2(255),
    REASON           VARCHAR2(32767),
    SIZE_BYTES       NUMBER,
    ORIGINATING_HOST VARCHAR2(255),
    OUTBOUND_IP      VARCHAR2(50),
    EMAIL_CLIENT     VARCHAR2(255),
    USER_AGENT       VARCHAR2(32767),
    SUBMITTED        TIMESTAMP(9) WITH TIME ZONE
)
/

create unique index UK_SMTP2GO_EVENT
    on SMTP2GO (EMAIL_ID, SYS_EXTRACT_UTC("EVENT_DATE"), EVENT_TYPE, RECIPIENT)
/

create table THIRD_DIA_DIA
(
    ID                NUMBER generated as identity
        primary key,
    CODIGO_GRUPO      NUMBER,
    ORIGEM            VARCHAR2(100),
    CPF               VARCHAR2(11) not null
        constraint UK_CPF
            unique,
    ID_DESCONHECIDO   NUMBER,
    NOME              VARCHAR2(100),
    STATUS_GERAL      CHAR,
    DATA_GERAL        DATE,
    STATUS_BIOMETRIA  VARCHAR2(20),
    STATUS_ASSOCIACAO VARCHAR2(100)
)
/

create table CONVENIO
(
    ID               NUMBER(10) generated as identity
        primary key,
    TITULO           VARCHAR2(255),
    HTML_REGULAMENTO CLOB,
    HTML_ASSOCIADO   CLOB,
    ACTIVE           NUMBER(1)
)
/

create table CONTENT
(
    ID               NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_210720".nextval generated as identity
		primary key,
    TENANT_CODE      VARCHAR2(50),
    CTYPE_CODE       VARCHAR2(50),
    CONTENTS         CLOB,
    TITLE            VARCHAR2(1000),
    CREATED_AT       DATE,
    UPDATED_AT       DATE,
    PUBLISHED_AT     DATE,
    IMAGE_BLOB       BLOB,
    IMAGE_MIME_TYPE  VARCHAR2(255),
    IMAGE_FILENAME   VARCHAR2(500),
    IMAGE_ALT        VARCHAR2(500),
    IMAGE_URL        VARCHAR2(2000),
    IMAGE_UPDATED_AT TIMESTAMP(6),
    CONTENT_FORMAT   VARCHAR2(100),
    SLUG             VARCHAR2(150),
    SORT_ORDER       NUMBER,
    STATUS           VARCHAR2(30) default 'published',
    AUTHOR_NAME      VARCHAR2(300),
    SOURCE_NAME      VARCHAR2(300),
    SOURCE_URL       VARCHAR2(1000),
    AUTHOR_ROLE      VARCHAR2(300),
    SUBTYPE          VARCHAR2(80)
)
/

comment on column CONTENT.AUTHOR_NAME is 'Nome do autor do conteúdo.'
/

comment on column CONTENT.SOURCE_NAME is 'Fonte/publicador do conteúdo. Não usar para cargo do autor.'
/

comment on column CONTENT.AUTHOR_ROLE is 'Cargo, função ou qualificação do autor. Ex.: Procurador Federal.'
/

comment on column CONTENT.SUBTYPE is 'Subtipo editorial opcional. Ex.: latest-reports para Últimos Informes usando ctype_code=news.'
/

create unique index IDX_CONTENT_TENANT_CTYPE_SLUG
    on CONTENT (CASE WHEN TRIM("SLUG") IS NOT NULL THEN LOWER("TENANT_CODE") END,
                CASE WHEN TRIM("SLUG") IS NOT NULL THEN LOWER("CTYPE_CODE") END,
                CASE WHEN TRIM("SLUG") IS NOT NULL THEN LOWER(NVL("SUBTYPE", '-')) END,
                CASE WHEN TRIM("SLUG") IS NOT NULL THEN LOWER(TRIM("SLUG")) END)
/

create table EMAIL_BLACKLIST
(
    ID         NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_214466".nextval generated by default on null as identity
		constraint PK_EMAIL_BLACKLIST
			primary key,
    EMAIL      VARCHAR2(255)
        constraint UQ_EMAIL_BLACKLIST_EMAIL
            unique,
    REASON     CLOB,
    CREATED_AT TIMESTAMP(6) default current_timestamp
)
/

create table EMAIL_QUEUE
(
    ID                 NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_214477".nextval generated as identity
		constraint EMAIL_QUEUE_PK
			primary key,
    EMAIL_CAMPAIGN_ID  NUMBER
        constraint EMAIL_QUEUE_CAMPAIGN_FK
            references EMAIL_CAMPAIGN,
    MEMBER_ID          NUMBER,
    MEMBER_INSERT_DATE DATE,
    PERSON_ID          NUMBER,
    EMAIL              VARCHAR2(255) not null,
    STATUS             VARCHAR2(20) default 'pending'
        constraint EMAIL_QUEUE_STATUS_CK
            check (status IN ('pending', 'sent', 'error', 'invalid_email', 'processing')),
    LAST_TRY           DATE,
    OPENED_AT          DATE,
    NAME               VARCHAR2(255),
    COMPANY            VARCHAR2(100),
    HOME_UF            CHAR(2),
    WORK_UF            CHAR(2),
    BLOCKED            NUMBER(1)    default 0
        constraint EMAIL_QUEUE_BLOCKED_CK
            check (blocked IN (0, 1)),
    PRIORITY           NUMBER       default 10,
    ERROR              CLOB,
    CREATED_AT         DATE         default SYSDATE
)
/

create index EMAIL_QUEUE_EMAIL_IDX
    on EMAIL_QUEUE (EMAIL)
/

create index EMAIL_QUEUE_MEMBER_INSERT_DATE_IDX
    on EMAIL_QUEUE (MEMBER_INSERT_DATE)
/

create index EMAIL_QUEUE_STATUS_IDX
    on EMAIL_QUEUE (STATUS)
/

create index EMAIL_QUEUE_CAMPAIGN_IDX
    on EMAIL_QUEUE (EMAIL_CAMPAIGN_ID)
/

create table EMAIL_SEND_LOG
(
    ID                NUMBER(19)   default "WKSP_SINDICATTO"."ISEQ$$_214532".nextval generated by default on null as identity
		constraint PK_EMAIL_SEND_LOG
			primary key,
    EMAIL_QUEUE_ID    NUMBER(19),
    EMAIL_CAMPAIGN_ID NUMBER(19),
    EMAIL             VARCHAR2(255)                     not null,
    SUBJECT           VARCHAR2(500),
    STATUS            VARCHAR2(30) default 'attempt'    not null
        constraint CK_EMAIL_SEND_LOG_STATUS
            check (status IN (
                              'attempt',
                              'sent',
                              'error',
                              'invalid_email'
                )),
    ERROR             CLOB,
    CREATED_AT        TIMESTAMP(6) default systimestamp not null
)
/

create index IDX_EMAIL_SEND_LOG_CREATED_AT
    on EMAIL_SEND_LOG (CREATED_AT)
/

create index IDX_EMAIL_SEND_LOG_EMAIL
    on EMAIL_SEND_LOG (EMAIL)
/

create index IDX_EMAIL_SEND_LOG_EMAIL_EMAIL
    on EMAIL_SEND_LOG (EMAIL_CAMPAIGN_ID, EMAIL)
/

create index IDX_EMAIL_SEND_LOG_QUEUE
    on EMAIL_SEND_LOG (EMAIL_QUEUE_ID)
/

create table CTYPE
(
    ID             NUMBER    default "WKSP_SINDICATTO"."ISEQ$$_214557".nextval generated by default on null as identity
		primary key,
    TENANT_CODE    VARCHAR2(50)        not null,
    CODE           VARCHAR2(100),
    ID_PERFIL_OLD  NUMBER,
    TAG_PERFIL_OLD VARCHAR2(100),
    NAME           VARCHAR2(50)        not null,
    PLURAL_NAME    VARCHAR2(50)        not null,
    DESCRIPTION    VARCHAR2(200),
    READ_ONLY      NUMBER(1) default 1 not null,
    IS_ADMIN       NUMBER(1) default 1 not null,
    ACTIVE         NUMBER(1) default 1 not null,
    HASH           as (ORA_HASH("CODE")),
    constraint UK_CTYPE_TENANT_CODE
        unique (TENANT_CODE, CODE)
)
/

create table "--PERMISSION"
(
    ID            NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_216471".nextval generated as identity
		primary key,
    TENANT_CODE   VARCHAR2(50)                      not null,
    ETYPE_CODE    VARCHAR2(50)                      not null,
    ACTION_CODE   VARCHAR2(50)                      not null,
    RESOURCE_CODE VARCHAR2(100)                     not null,
    REQUIRES_DEV  NUMBER(1)    default 0            not null
        constraint CK_PERMISSION_REQUIRES_DEV
            check (requires_dev IN (0, 1)),
    ACTIVE        CHAR         default 'Y'          not null
        constraint CK_PERMISSION_ACTIVE
            check (active IN ('Y', 'N')),
    CREATED_AT    TIMESTAMP(6) default SYSTIMESTAMP not null,
    constraint UQ_PERMISSION
        unique (TENANT_CODE, ETYPE_CODE, ACTION_CODE, RESOURCE_CODE, REQUIRES_DEV)
)
/

create table ETYPE_PERMISSION
(
    ID           NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_216505".nextval generated as identity
		primary key,
    TENANT_CODE  VARCHAR2(50)                      not null,
    ETYPE_CODE   VARCHAR2(50)                      not null,
    PAGE_ALIAS   VARCHAR2(100)                     not null,
    ACTION_CODE  VARCHAR2(50)                      not null,
    REQUIRES_DEV NUMBER(1)    default 0            not null
        constraint CK_ETYPE_PERMISSION_REQUIRES_DEV
            check (requires_dev IN (0, 1)),
    ACTIVE       NUMBER(1)    default 1            not null
        check (active IN (0, 1)),
    CREATED_AT   TIMESTAMP(6) default systimestamp not null,
    constraint UQ_ETYPE_PERMISSION
        unique (TENANT_CODE, ETYPE_CODE, PAGE_ALIAS, ACTION_CODE, REQUIRES_DEV),
    constraint FK_ETYPE_PERMISSION_ETYPE
        foreign key (TENANT_CODE, ETYPE_CODE) references ETYPE (TENANT_CODE, CODE),
    constraint FK_ETYPE_PERMISSION_TENANT_PERMISSION
        foreign key (TENANT_CODE, PAGE_ALIAS) references TENANT_PERMISSION (TENANT_CODE, PAGE_ALIAS)
)
/

create table VOTING
(
    ID          NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_216640".nextval generated by default on null as identity
		constraint PK_VOTING
			primary key,
    TENANT_CODE VARCHAR2(50)                      not null
        constraint FK_VOTING_TENANT
            references TENANT (CODE),
    TITLE       VARCHAR2(500)                     not null,
    DESCRIPTION CLOB,
    STARTS_AT   TIMESTAMP(6),
    ENDS_AT     TIMESTAMP(6),
    IS_ACTIVE   NUMBER(1)    default 1            not null
        constraint CK_VOTING_ACTIVE
            check (is_active IN (0, 1)),
    CREATED_AT  TIMESTAMP(6) default systimestamp not null,
    UPDATED_AT  TIMESTAMP(6)
)
/

create table VOTING_QUESTION
(
    ID             NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_216645".nextval generated by default on null as identity
		constraint PK_VOTING_QUESTION
			primary key,
    VOTING_ID      NUMBER                            not null
        constraint FK_VOTING_QUESTION_VOTING
            references VOTING,
    QUESTION_ORDER NUMBER                            not null,
    QUESTION_TEXT  CLOB                              not null,
    IS_ACTIVE      NUMBER(1)    default 1            not null
        constraint CK_VOTING_QUESTION_ACTIVE
            check (is_active IN (0, 1)),
    CREATED_AT     TIMESTAMP(6) default systimestamp not null,
    UPDATED_AT     TIMESTAMP(6),
    constraint UK_VOTING_QUESTION_ID_VOTING
        unique (ID, VOTING_ID),
    constraint UK_VOTING_QUESTION_ORDER
        unique (VOTING_ID, QUESTION_ORDER)
)
/

create table VOTING_OPTION
(
    ID                 NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_216652".nextval generated by default on null as identity
		constraint PK_VOTING_OPTION
			primary key,
    VOTING_QUESTION_ID NUMBER                            not null
        constraint FK_VOTING_OPTION_QUESTION
            references VOTING_QUESTION,
    OPTION_ORDER       NUMBER                            not null,
    OPTION_TEXT        VARCHAR2(100)                     not null,
    IS_ACTIVE          NUMBER(1)    default 1            not null
        constraint CK_VOTING_OPTION_ACTIVE
            check (is_active IN (0, 1)),
    CREATED_AT         TIMESTAMP(6) default systimestamp not null,
    UPDATED_AT         TIMESTAMP(6),
    constraint UK_VOTING_OPTION_ID_QUESTION
        unique (ID, VOTING_QUESTION_ID),
    constraint UK_VOTING_OPTION_ORDER
        unique (VOTING_QUESTION_ID, OPTION_ORDER)
)
/

create table VOTING_ANSWER
(
    ID                 NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_216657".nextval generated by default on null as identity
		constraint PK_VOTING_ANSWER
			primary key,
    VOTING_ID          NUMBER                            not null
        constraint FK_VOTING_ANSWER_VOTING
            references VOTING,
    VOTING_QUESTION_ID NUMBER                            not null
        constraint FK_VOTING_ANSWER_QUESTION
            references VOTING_QUESTION,
    VOTING_OPTION_ID   NUMBER                            not null,
    MEMBER_ID          NUMBER                            not null
        constraint FK_VOTING_ANSWER_MEMBER
            references MEMBER,
    ENTITY_ID          NUMBER
        constraint FK_VOTING_ANSWER_ENTITY
            references ENTITY,
    ANSWERED_AT        TIMESTAMP(6) default systimestamp not null,
    IP_ADDRESS         VARCHAR2(45),
    constraint UK_VOTING_ANSWER_ONCE
        unique (VOTING_ID, VOTING_QUESTION_ID, MEMBER_ID),
    constraint FK_VOTING_ANSWER_OPTION_QUESTION
        foreign key (VOTING_OPTION_ID, VOTING_QUESTION_ID) references VOTING_OPTION (ID, VOTING_QUESTION_ID),
    constraint FK_VOTING_ANSWER_QUESTION_VOTING
        foreign key (VOTING_QUESTION_ID, VOTING_ID) references VOTING_QUESTION (ID, VOTING_ID)
)
/

create table CONTENT_ATTACHMENT
(
    ID              NUMBER       default "WKSP_SINDICATTO"."ISEQ$$_217236".nextval generated by default on null as identity
		primary key,
    CONTENT_ID      NUMBER                            not null
        constraint FK_CONTENT_ATTACHMENT_CONTENT
            references CONTENT
                on delete cascade,
    SORT_ORDER      NUMBER       default 0            not null,
    TITLE           VARCHAR2(500)                     not null,
    FILE_URL        VARCHAR2(2000)                    not null,
    FILE_NAME       VARCHAR2(500),
    MIME_TYPE       VARCHAR2(200),
    FILE_SIZE_BYTES NUMBER,
    IS_EXTERNAL     CHAR         default 'Y'
        check (is_external IN ('Y', 'N')),
    CREATED_AT      TIMESTAMP(6) default systimestamp not null,
    UPDATED_AT      TIMESTAMP(6) default systimestamp not null
)
/

create materialized view MV_PARTNERSHIP_PARTNERS
    refresh fast on commit
as
SELECT p.tenant_code, p.parent_code, p.role
FROM partnership p
WHERE role = 'partner'
/

create view VW_RAW_ETYPE as
SELECT tenant_code
    , hash
    , code
    , name
    , plural_name
    , tag_perfil_old

FROM etype t
WHERE 1 = 1
/

create view VW_ETYPE as
SELECT "TENANT_CODE","HASH","CODE","NAME","PLURAL_NAME","TAG_PERFIL_OLD"

FROM vw_raw_etype
WHERE 1 = 1
    AND lower(tenant_code) = lower(v('G_TENANT_CODE')) OR sys_context('USERENV', 'MODULE') = 'DataGrip'
/

create view VW_RAW_TICKET as
SELECT TO_CHAR(open_date, 'dd/mm/yyyy') open_date_str
    , TO_CHAR(done_date, 'dd/mm/yyyy') done_date_str
    , ticket."ID",ticket."TENANT_CODE",ticket."TENANT_ID",ticket."TITLE",ticket."STATUS",ticket."OPEN_DATE",ticket."DUE_DATE",ticket."DONE_DATE",ticket."DESCRIPTION",ticket."URGENT"

FROM ticket
/

create view VW_TICKET as
SELECT "OPEN_DATE_STR","DONE_DATE_STR","ID","TENANT_CODE","TENANT_ID","TITLE","STATUS","OPEN_DATE","DUE_DATE","DONE_DATE","DESCRIPTION","URGENT"

FROM vw_raw_ticket
WHERE 1 = 1
    AND LOWER(tenant_code) = LOWER(v('G_TENANT_CODE'))
/

create view VW_RAW_EMAIL_CAMPAIGN as
SELECT "ID","TENANT_CODE","TENANT_ID","SUBJECT","BODY_HTML","BODY_TEXT","SENDER_NAME","SENDER_EMAIL","SEND_DATE","STATUS","RECIPIENT_COUNTRY_CODE","RECIPIENT_UF_CODE","CREATED_AT","UPDATED_AT","TOTAL_EMAILS_SENT","TOTAL_EMAILS_DELIVERED","OPENED_PERCENT","OPENED_COUNT","SUBJECT_AI"
FROM email_campaign
/

create view VW_EMAIL_CAMPAIGN as
SELECT "ID","TENANT_CODE","TENANT_ID","SUBJECT","BODY_HTML","BODY_TEXT","SENDER_NAME","SENDER_EMAIL","SEND_DATE","STATUS","RECIPIENT_COUNTRY_CODE","RECIPIENT_UF_CODE","CREATED_AT","UPDATED_AT","TOTAL_EMAILS_SENT","TOTAL_EMAILS_DELIVERED","OPENED_PERCENT","OPENED_COUNT","SUBJECT_AI"

FROM vw_raw_email_campaign
WHERE 1 = 1
        AND LOWER(tenant_code) = LOWER(v('G_TENANT_CODE')) OR
    sys_context('USERENV', 'MODULE') = 'DataGrip'
/

create view VW_MEMBROS_POR_PERFIL as
SELECT e.plural_name, COUNT(*) total
FROM member m
LEFT JOIN etype e ON e.code = m.etype_code AND e.tenant_code = m.tenant_code
WHERE 1 = 1

    --
    AND m.active = 1
    AND LOWER(m.tenant_code) = LOWER(v('G_TENANT_CODE'))

GROUP BY e.plural_name
ORDER BY COUNT(*)
/

create view VW_SENDER_INVALID as
SELECT "EMAIL","GROUPS","PHONE","EMAIL_STATUS","SMS_STATUS","TRANSACTIONAL_EMAIL_STATUS","TRANSACTIONAL_SMS_STATUS","LOCATION","CREATED","LAST_NAME","FIRST_NAME","IDADE","SENHA","ENTIDADE","UF","ID_MEMBRO","DATA_NASCIMENTO","ID_PESSOA","CPF"
FROM sender
WHERE 1 = 1
    AND email_status <> 'active'
    AND transactional_email_status <> 'active'
ORDER BY email
/

create view VW_SMTP2GO as
SELECT "ID","EMAIL_ID","EVENT_DATE","EVENT_TYPE","USERNAME","FROM_EMAIL","REPLY_TO","RECIPIENT","SUBJECT","REASON","SIZE_BYTES","ORIGINATING_HOST","OUTBOUND_IP","EMAIL_CLIENT","USER_AGENT","SUBMITTED"
FROM smtp2go
WHERE 1 = 1
    -- 20260621-0249 email suporte@sindicatto.com
    AND username = 'api-207565AC5AEA'
/

create view VW_MAIL_QUEUE as
SELECT mail.subject mail_subject
    , COUNT(*) total_enviados
    , vw.total_hard_bounces
    , vw.total_soft_bounces
    , vw.total_spam
    , mail_queue.created_at
FROM mail_queue
LEFT JOIN mail ON mail.id = mail_id
LEFT JOIN vw_smtp2go vw ON vw.label = mail.subject
GROUP BY mail_id, mail.subject, vw.total_hard_bounces, vw.total_soft_bounces, vw.total_spam, mail_queue.created_at

UNION
SELECT 'ASAnews 09/2025 – 25% Casas Bahia, 20% Nike Jordan, 15% Dr. Lava Tudo e 12% Riachuelo', 6415, 12, 38, 6, TO_DATE('2025-09-01 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews 09/2025 – HR-V e City 2026, 30% Pague Menos, 10% Morana e ofertas Renner', 6412, 10, 29, 5, TO_DATE('2025-09-01 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews 09/2025 – 80% Dafiti, 15% Mizuno e Mash, 12% Riachuelo e ofertas Zattini', 6411, 3, 9, 2, TO_DATE('2025-09-01 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews 09/2025 – Descontos Semanais: Pilates, Psicologia, Moda e Hotelaria', 6411, 2, 7, 1, TO_DATE('2025-09-11 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews 09/2025 – 20% Movida, 10% COC Lago Norte, 10% Escola DNA, 7% PneuStore e 10% Emma', 6415, 4, 9, 2, TO_DATE('2025-09-18 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual

UNION
SELECT 'ASAnews – 20% CVC e Nacional Inn, R$200 Decolar, 10% Vila Galé, até 20% Hplus', 6420, 9, 5, 6, TO_DATE('2025-11-13 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – Até 30% Bionatus, 22% Escola Canadense, 20% Progresso Bilíngue, 15% Dom José, 10% COC', 6415, 10, 5, 2, TO_DATE('2025-11-27 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – 20% Nike e Sanavita, Curso de Francês CF, Veneza Water e APLI', 6415, 8, 3, 4, TO_DATE('2025-12-11 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – 25% CIBL, 15% Amobeleza e Evino, 12% Stanley, 10% Imaginarium', 6415, 7, 7, 4, TO_DATE('2025-12-18 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual

UNION
SELECT 'ASAnews – Benefício Auto | Compra de Honda 0km com desconto ampliado para 7% (ASAcar)', 6415, 6, 7, 2, TO_DATE('2026-01-08 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews - 18% Insider, 15% Hering e Zattini, 12% Riachuelo, 10% Marcyn', 6415, 4, 7, 3, TO_DATE('2026-01-15 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
-- union select 'ASAnews – 15% Salon Line, Amobeleza e Océane',6417,5,5,3,  TO_DATE('2026-01-22 00:00','YYYY-MM-DD HH24:MI') from dual
-- union select '',6415,4,7,3,  TO_DATE('2026- 00:00','YYYY-MM-DD HH24:MI') from dual
UNION
SELECT 'ASAnews – ate 55% CEUB, 50% IESLA, ate 45% Anima e 10% Mackenzie', 6416, 3, 8, 9, TO_DATE('2026-01-29 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – 10% IDP, ate 12% CESAR, 50% Faculdade Supremo e 20% UniProcessus', 6415, 4, 4, 4, TO_DATE('2026-02-05 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – 10% Midea, 40% Domino’s Pizza, 15% O Boticário, 10% Morana e 10% O Francês Gravataaria', 6715, 8, 3, 11, TO_DATE('2026-02-13 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – 15% Educandário Santa Mônica, até 18% Sigma, 50% Localiza Meoo, até 45% Berlitz e até 35% Seguros do Brasil', 6705, 7, 8, 9, TO_DATE('2026-02-17 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – 35% Descomplica, 25% Merece Saúde, 15% Nutrify, 5% Electrolux e Continental e até 10% Shoestock', 6305, 11, 7, 11, TO_DATE('2026-02-27 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
-- 20260312                                                                                                                                                                                         --
UNION
SELECT 'ASAnews – 15% Quadros Ram, Black Fralda, 10–15% UTI Saúde Med, 20% Dr. Victor Almeida e 20% WineC', 6301, 7, 5, 8, TO_DATE('2026-03-05 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – Sorteio Adega Climatizada Brastemp 12 garrafas (APROM-BH)', 6301, 7, 5, 8, TO_DATE('2026-03-05 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – até 30% Sabin, 20% Dom Bosco, até 70% Approve + 20% extra, 10% Kaspersky e até 50% Mash', 6305, 5, 4, 0, TO_DATE('2026-03-16 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – 15% Spa Saúde, 25% Hering (Mês da Mulher), 15% + 5% Elia Spa, 25% Luckau (Páscoa) e desconto progressivo Travelex Confidence', 6305, 2, 5, 0, TO_DATE('2026-03-16 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – 20% Primeira, 5% MinutaIA, R$1000 Geely Eurovia, 20% Othon e 15% Insider', 6345, 6, 5, 2, TO_DATE('2026-03-27 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – ate 12% Movida, ate 25% PontoFrio, 15% Vivara, R$25 Evino e 5% Ikesaki', 6347, 5, 7, 1, TO_DATE('2026-04-02 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – Sorteio Adega Brastemp 12 garrafas exclusiva AMPCON', 98, 2, 1, 1, TO_DATE('2026-04-02 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'Sorteio Adega Climatizada ASAclub exclusiva 12 garrafas (SINPROFAZ)', 1100, 3, 2, 3, TO_DATE('2026-04-09 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – 15% Olympikus e Under Armour, até 70% Zattini, 25% Extra e 60% Netshoes', 6351, 8, 8, 3, TO_DATE('2026-04-10 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – Sorteio Adega Brastemp 12 garrafas exclusiva SINPROFAZ ate 24/04/26', 1100, 3, 2, 3, TO_DATE('2026-04-14 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – Sorteio Especial Adega Brastemp 12 garrafas para associados AMPCON inscrição ate 24/04/26', 98, 1, 1, 1, TO_DATE('2026-04-16 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – 15% Pneu Store, bonus R$13.200 Chevrolet e descontos Drogasil, Droga Raia, Pague Menos e Extrafarma', 6555, 7, 6, 4, TO_DATE('2026-04-22 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – até 40% Natura, 15% Oceane, 25% Hering e preços de atacado Atacadão Dia a Dia', 6558, 7, 7, 4, TO_DATE('2026-04-22 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – terapias Fiore, R$50 Giuliana Flores, 25% Gocase, até 25% Hoteis.com e até 35% Ibmec', 6558, 8, 9, 4, TO_DATE('2026-04-22 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – 20% Hot Park, 10% Snowland, 10% Beto Carrero World e até 20% Porto Serviço', 6559, 11, 4, 5, TO_DATE('2026-04-22 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
UNION
SELECT 'ASAnews – 15% Nação Verde, 10% Brasas, 20% Dom Bosco, 15% Eliá Spa e CheckUp Center BH', 6559, 9, 6, 3, TO_DATE('2026-04-22 00:00', 'YYYY-MM-DD HH24:MI')
FROM dual
/

create view VW_MAIL_QUEUE_TO_SEND as
SELECT 1 AS flag_send
    , q.id
    , q.mail_id
    , q.email
    , q.name
    , q.member_insert_date
    , q.status
    , m.from_name AS fromname
    , m.from_email AS fromemail
    , m.subject
    , m.html
FROM wksp_sindicatto.mail_queue q
LEFT JOIN wksp_sindicatto.mail m
          ON m.id = q.mail_id
WHERE 1 = 1
    AND q.status = 'pending'
    AND q.mail_id IN (0036)
    AND q.email IS NOT NULL
    AND NOT exists (SELECT 1
                    FROM wksp_sindicatto.mail_blacklist b
                    WHERE lower(trim(b.email)) = lower(trim(q.email)))
-- AND q.EMAIL IN ('inattox@gmail.com', 'danielmaiax@gmail.com', 'dev@inatto.com')
ORDER BY q.priority
    , q.member_insert_date DESC
    , q.id DESC
/

create view VW_EMAIL_QUEUE_TO_SEND as
SELECT 1 AS flag_send
    , q.id
    , q.email_campaign_id
    , q.email
    , q.name
    , q.member_insert_date
    , q.status
--     , c.from_name AS fromname
--     , c.from_email AS fromemail
    , c.subject
    , c.body_html
FROM email_queue q
LEFT JOIN email_campaign c ON c.id = q.email_campaign_id
WHERE 1 = 1
--     AND q.status = 'pending'
    AND q.email_campaign_id IN (0361)
    AND q.email IS NOT NULL
    AND NOT exists (SELECT 1
                    FROM wksp_sindicatto.email_blacklist b
                    WHERE lower(trim(b.email)) = lower(trim(q.email)))
    AND q.email IN ('inattox@gmail.com', 'danielmaiax@gmail.com', 'dev@inatto.com', 'sindicattox@gmail.com')
ORDER BY q.priority
    , q.member_insert_date DESC
    , q.id DESC
/

create PROCEDURE prc_create_user (
    p_user IN VARCHAR2,
    p_email IN VARCHAR2,
    p_password IN VARCHAR2
) IS
    v_ws_id NUMBER;

BEGIN

    --
    v_ws_id := apex_util.find_security_group_id(p_workspace => UPPER('SINDICATTO'));
    apex_util.set_security_group_id(v_ws_id);

    apex_util.create_user(
            p_user_name => p_user,
            p_email_address => p_email,
            p_web_password => p_password,
            p_web_password_format => 'CLEAR_TEXT',
            p_developer_privs => 'END_USER', -- ou 'ADMIN:CREATE:DATA_LOADER:EDIT:HELP:MONITOR:SQL' para admin
            p_default_schema => 'WKSP_SINDICATTO',
            p_allow_access_to_schemas => 'WKSP_SINDICATTO',
            p_account_locked => 'N',
            p_change_password_on_first_use=> 'N'
    );

    COMMIT;
END;
/

create FUNCTION remove_non_digits(p_text IN VARCHAR2)
RETURN VARCHAR2 IS
    v_result VARCHAR2(4000);
BEGIN
    v_result := REGEXP_REPLACE(p_text, '[^0-9]', '');
    RETURN v_result;
END;
/

create FUNCTION is_dev
    RETURN BOOLEAN IS
    is_dev SMALLINT;
BEGIN

    -- TODO 20250630
    SELECT is_dev
    INTO is_dev
    FROM member
    WHERE 1 = 1
        AND id = v('G_MEMBER_ID');
    --         AND id = 10369

    IF (is_dev = 1) THEN
        RETURN TRUE;
    END IF;

    RETURN FALSE;

END;
/

create FUNCTION is_manager
    RETURN BOOLEAN IS
BEGIN
    return TRUE;

    -- TODO 20250630
    IF LOWER(apex_application.g_user) IN ('asa.convenios@asaclub.org.br', 'dev') THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END;
/

create PROCEDURE prc_set_member_by_hash (
    p_tenant_code IN varchar2, p_cpf_hash IN varchar2
) AS

    v_member_id number;
    v_entity_id number;
    v_entity_name varchar2(200);
    v_etype_name varchar2(100);
    v_etype_code varchar2(100);

BEGIN

    -- Recupera o ID do membro, Nome da Entidade (Pessoa) e Nome do Perfil
    SELECT m.id, e.name, t.name, m.etype_code, m.entity_id
    INTO v_member_id, v_entity_name, v_etype_name, v_etype_code, v_entity_id
    FROM member m
    LEFT JOIN entity e ON m.entity_id = e.id
    LEFT JOIN etype t ON t.code = m.etype_code
    WHERE 1 = 1
        AND m.active = 1
        AND e.active = 1
        AND lower(m.tenant_code) = lower(p_tenant_code)
        -- TODO 20250713 criar indice
        AND lower(standard_hash(lower(m.tenant_code) || lower(nvl(t.tag_perfil_old, '')) || nvl(e.br_cpf, dbms_random.string('X', 40)), 'SHA1')) = lower(p_cpf_hash)
        FETCH FIRST 1 ROW ONLY -- 20250706 nao poderia ter mais de 1 CPF
    ;

    --
    --     apex_util.set_session_state('G_CPF_HASH', p_cpf_hash);
    apex_util.set_session_state('G_MEMBER_ID', v_member_id);
    apex_util.set_session_state('G_ENTITY_ID', v_entity_id);
    apex_util.set_session_state('G_ENTITY_NAME', v_entity_name);
    apex_util.set_session_state('G_ETYPE_NAME', v_etype_name);
    apex_util.set_session_state('G_ETYPE_CODE', v_etype_code);

    -- debug
    --     dbms_output.put_line('p_cpf_hash: ' || p_cpf_hash);
    dbms_output.put_line('p_tenant_code: ' || p_tenant_code);
    dbms_output.put_line('v_member_id: ' || v_member_id);
    dbms_output.put_line('v_entity_name: ' || v_entity_name);
    dbms_output.put_line('v_etype_name: ' || v_etype_name);
    dbms_output.put_line('v_etype_code: ' || v_etype_code);
    dbms_output.put_line('v_entity_id: ' || v_entity_id);

EXCEPTION

    WHEN no_data_found THEN raise_application_error(-20001, 'Invalid chash.');

END;
/

create PROCEDURE prc_set_config (p_tenant_code IN VARCHAR2, p_cpf_hash IN VARCHAR2 DEFAULT NULL) AS
    v_tid         NUMBER;
    v_cookie      owa_cookie.cookie;
    v_tenant_code VARCHAR2(100);
    v_tenant_name VARCHAR2(100);
BEGIN

    -- 1) ID Tenant por parametro? Prioritario
    IF (p_tenant_code IS NOT NULL) THEN
        owa_cookie.remove('COOKIE_TENANT_ID', v_tid, '/ords');
        SELECT id INTO v_tid FROM tenant WHERE LOWER(code) = LOWER(p_tenant_code);
    END IF;

    -- 2) ID Tenant por cookie?
    -- se v_tid for nulo, tenta pegar v_cookie - NAO RODA NO CONSOLE/DATAGRIP
    v_cookie := owa_cookie.get('COOKIE_TENANT_ID');
    IF v_tid IS NULL AND v_cookie.vals.count > 0 THEN
        v_tid := v_cookie.vals(1);
    END IF;

    -- 3) Nao tem cookie nem param, pega default
    IF v_tid IS NULL THEN
        SELECT id INTO v_tid FROM tenant WHERE LOWER(code) = 'sindicatto';
    END IF;

    -- seta v_cookie com o v_tid atual - path /ords é parte da chave do cookie (Ver F12 - 20250626)
    owa_cookie.send('COOKIE_TENANT_ID', v_tid, NULL, '/ords');

    -- busca do banco
    BEGIN

        --
        SELECT id, code, name INTO v_tid, v_tenant_code, v_tenant_name FROM tenant WHERE id = v_tid;

        -- 20250703 login cpf
        IF (p_cpf_hash IS NOT NULL) THEN
            prc_set_member_by_hash(v_tenant_code, p_cpf_hash);
        END IF;

        --
        apex_util.set_session_state('G_TENANT_ID', v_tid);
        apex_util.set_session_state('G_TENANT_CODE', v_tenant_code);
        apex_util.set_session_state('G_TENANT_CODE_LOWER', LOWER(v_tenant_code));
        apex_util.set_session_state('G_TENANT_NAME', v_tenant_name);

    EXCEPTION
        WHEN no_data_found THEN
            RAISE_APPLICATION_ERROR(-20001, 'Invalid tenant.');
    END;

END;
/

create FUNCTION is_asaclub
    RETURN BOOLEAN IS
BEGIN

    IF (LOWER(v('G_TENANT_CODE')) = 'asaclub') THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;

END;
/

create PROCEDURE prc_big_bang IS

BEGIN

    apex_util.set_session_time_zone('America/Sao_Paulo');
--     ALTER SESSION set TIME_ZONE = 'America/Sao_Paulo';

END;
/

create FUNCTION mask_br_cnpj(p_cnpj VARCHAR2)
    RETURN VARCHAR2
    DETERMINISTIC IS
BEGIN
    RETURN REGEXP_REPLACE(p_cnpj, '(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})', '\1.\2.\3/\4-\5');
END;
/

create FUNCTION mask_br_cpf(p_cpf VARCHAR2)
    RETURN VARCHAR2 DETERMINISTIC IS
BEGIN
    IF p_cpf IS NULL OR NOT REGEXP_LIKE(p_cpf, '^[0-9]{11}$') THEN
        RETURN '';
    END IF;
    RETURN SUBSTR(REGEXP_REPLACE(p_cpf, '(\d{3})(\d{3})(\d{3})(\d{2})', '\1.\2.\3-\4'), 1, 20);
END;
/

create FUNCTION mask_br_date(p_date DATE)
    RETURN VARCHAR2 DETERMINISTIC IS
BEGIN
    RETURN TO_CHAR(p_date, 'dd/mm/yyyy');
END;
/

create view VW_PROCESSO_BR_SERVIDOR as
SELECT id id2
    , nome nome2
    , cpf_mask cpf2
    , p."ID",p."NOME",p."CPF",p."SITUACAO_FUNCIONAL",p."NOME_PENSIONISTA",p."CPF_PENSIONISTA",p."AUTOR_ACAO",p."OBJETO_ACAO",p."ESCRITORIO_RESPONSAVEL",p."PARTE_CONTRARIA",p."NR_PROCESSO",p."VARA_PROCESSO",p."NR_CUMPRIMENTO",p."NR_EMBARGOS",p."VARA_CUMPRIMENTO",p."VALOR_EXECUTADO",p."VALOR_ACAO",p."VALOR_ACORDO_AGU",p."NR_PRECATORIO",p."VALOR_PRECATORIO",p."DATA_EXPEDICAO_PRECATORIO",p."NR_SUPLEMENTAR",p."VALOR_SUPLEMENTAR",p."DATA_EXPEDICAO_SUPLEMENTAR",p."VALOR_DEVOLVIDO",p."DATA_DEVOLUCAO",p."CPF_MASK",p."CPF_PENSIONISTA_MASK",p."DATA_EXPEDICAO_PRECATORIO_MASK",p."DATA_EXPEDICAO_SUPLEMENTAR_MASK",p."DATA_DEVOLUCAO_MASK",p."TENANT_CODE"

FROM processo_br p
WHERE 1 = 1
        AND p.nome_pensionista IS NULL
        AND LOWER(tenant_code) = LOWER(v('G_TENANT_CODE')) OR sys_context('USERENV', 'MODULE') = 'DataGrip'
/

create view VW_RAW_PROCESSO_BR as
SELECT 1 dummy
    , t.name tenant_name
    , processo_br."ID",processo_br."TENANT_CODE",processo_br."NOME",processo_br."CPF",processo_br."CPF_MASK",processo_br."SITUACAO_FUNCIONAL",processo_br."NOME_PENSIONISTA",processo_br."CPF_PENSIONISTA",processo_br."CPF_PENSIONISTA_MASK",processo_br."AUTOR_ACAO",processo_br."OBJETO_ACAO",processo_br."ESCRITORIO_RESPONSAVEL",processo_br."PARTE_CONTRARIA",processo_br."NR_PROCESSO",processo_br."VARA_PROCESSO",processo_br."NR_CUMPRIMENTO",processo_br."NR_EMBARGOS",processo_br."VARA_CUMPRIMENTO",processo_br."VALOR_EXECUTADO",processo_br."VALOR_ACAO",processo_br."VALOR_ACORDO_AGU",processo_br."NR_PRECATORIO",processo_br."VALOR_PRECATORIO",processo_br."DATA_EXPEDICAO_PRECATORIO",processo_br."DATA_EXPEDICAO_PRECATORIO_MASK",processo_br."NR_SUPLEMENTAR",processo_br."VALOR_SUPLEMENTAR",processo_br."DATA_EXPEDICAO_SUPLEMENTAR",processo_br."DATA_EXPEDICAO_SUPLEMENTAR_MASK",processo_br."VALOR_DEVOLVIDO",processo_br."DATA_DEVOLUCAO",processo_br."DATA_DEVOLUCAO_MASK",processo_br."ULTIMO_ANDMENTO",processo_br."SITUACAO_PAGAMENTO",processo_br."SITUACAO_CUMPRIMENTO_SENTENCA",processo_br."SITUACAO_EMBARGOS_EXECUCAO"

FROM processo_br
LEFT JOIN tenant t ON t.code = processo_br.tenant_code
/

create view VW_PROCESSO_BR as
SELECT DISTINCT "DUMMY","TENANT_NAME","ID","TENANT_CODE","NOME","CPF","CPF_MASK","SITUACAO_FUNCIONAL","NOME_PENSIONISTA","CPF_PENSIONISTA","CPF_PENSIONISTA_MASK","AUTOR_ACAO","OBJETO_ACAO","ESCRITORIO_RESPONSAVEL","PARTE_CONTRARIA","NR_PROCESSO","VARA_PROCESSO","NR_CUMPRIMENTO","NR_EMBARGOS","VARA_CUMPRIMENTO","VALOR_EXECUTADO","VALOR_ACAO","VALOR_ACORDO_AGU","NR_PRECATORIO","VALOR_PRECATORIO","DATA_EXPEDICAO_PRECATORIO","DATA_EXPEDICAO_PRECATORIO_MASK","NR_SUPLEMENTAR","VALOR_SUPLEMENTAR","DATA_EXPEDICAO_SUPLEMENTAR","DATA_EXPEDICAO_SUPLEMENTAR_MASK","VALOR_DEVOLVIDO","DATA_DEVOLUCAO","DATA_DEVOLUCAO_MASK","ULTIMO_ANDMENTO","SITUACAO_PAGAMENTO","SITUACAO_CUMPRIMENTO_SENTENCA","SITUACAO_EMBARGOS_EXECUCAO"

FROM vw_raw_processo_br
WHERE 1 = 1
    AND lower(tenant_code) = lower(v('G_TENANT_CODE')) OR sys_context('USERENV', 'MODULE') = 'DataGrip'
/

create view VW_PROCESSO_GROUPED as
SELECT DISTINCT nr_processo
    , LISTAGG(DISTINCT autor_acao, ', ') WITHIN GROUP (ORDER BY autor_acao) AS autor_acao
    , LISTAGG(DISTINCT objeto_acao, ', ') WITHIN GROUP (ORDER BY objeto_acao) AS objeto_acao
    , LISTAGG(DISTINCT escritorio_responsavel, ', ') WITHIN GROUP (ORDER BY escritorio_responsavel) AS escritorio_responsavel
    , LISTAGG(DISTINCT parte_contraria, ', ') WITHIN GROUP (ORDER BY parte_contraria) AS parte_contraria
    , LISTAGG(DISTINCT vara_processo, ', ') WITHIN GROUP (ORDER BY vara_processo) AS vara_processo
    , LISTAGG(DISTINCT vara_cumprimento, ', ') WITHIN GROUP (ORDER BY vara_cumprimento) AS vara_cumprimento

-- N     , LISTAGG(DISTINCT nr_cumprimento, ', ') WITHIN GROUP (ORDER BY nr_cumprimento) AS nr_cumprimento
-- N    , LISTAGG(DISTINCT nr_embargos, ', ') WITHIN GROUP (ORDER BY nr_embargos) AS nr_embargos
-- N     , LISTAGG(DISTINCT valor_executado, ', ') WITHIN GROUP (ORDER BY valor_executado) AS valor_executado
-- N     , LISTAGG(DISTINCT valor_acao, ', ') WITHIN GROUP (ORDER BY valor_acao) AS valor_acao
-- N     , LISTAGG(DISTINCT valor_acordo_agu, ', ') WITHIN GROUP (ORDER BY valor_acordo_agu) AS valor_acordo_agu
-- N     , listagg(distinct nr_precatorio, ', ') WITHIN GROUP (ORDER BY nr_precatorio) AS nr_precatorio
-- N     , listagg(distinct valor_precatorio, ', ') WITHIN GROUP (ORDER BY valor_precatorio) AS valor_precatorio
-- N     , listagg(distinct data_expedicao_precatorio_mask, ', ') WITHIN GROUP (ORDER BY data_expedicao_precatorio_mask) AS data_expedicao_precatorio_mask
-- N     , listagg(distinct nr_suplementar, ', ') WITHIN GROUP (ORDER BY nr_suplementar) AS nr_suplementar
-- N     , listagg(distinct valor_suplementar, ', ') WITHIN GROUP (ORDER BY valor_suplementar) AS valor_suplementar
-- N     , listagg(distinct data_expedicao_suplementar_mask, ', ') WITHIN GROUP (ORDER BY data_expedicao_suplementar_mask) AS data_expedicao_suplementar_mask
-- N     , listagg(distinct valor_devolvido, ', ') WITHIN GROUP (ORDER BY valor_devolvido) AS valor_devolvido
-- N     , listagg(distinct data_devolucao_mask, ', ') WITHIN GROUP (ORDER BY data_devolucao_mask) AS data_devolucao_mask

FROM vw_processo_br p
WHERE 1 = 1
GROUP BY nr_processo
ORDER BY nr_processo
/

create view VW_PROCESSO_BR_GROUPED as
SELECT DISTINCT 1 dummy
    , p.id
    , t.name tenant_name
    , t.code tenant_code
    , nr_processo
    , COUNT(DISTINCT cpf) AS partes_cpf
    , LISTAGG(DISTINCT autor_acao, ', ') WITHIN GROUP (ORDER BY autor_acao) AS autor_acao
    , LISTAGG(DISTINCT objeto_acao, ', ') WITHIN GROUP (ORDER BY objeto_acao) AS objeto_acao
    , LISTAGG(DISTINCT escritorio_responsavel, ', ') WITHIN GROUP (ORDER BY escritorio_responsavel) AS escritorio_responsavel
    , LISTAGG(DISTINCT parte_contraria, ', ') WITHIN GROUP (ORDER BY parte_contraria) AS parte_contraria
    , LISTAGG(DISTINCT vara_processo, ', ') WITHIN GROUP (ORDER BY vara_processo) AS vara_processo
    , LISTAGG(DISTINCT vara_cumprimento, ', ') WITHIN GROUP (ORDER BY vara_cumprimento) AS vara_cumprimento

-- N     , LISTAGG(DISTINCT nr_cumprimento, ', ') WITHIN GROUP (ORDER BY nr_cumprimento) AS nr_cumprimento
-- N    , LISTAGG(DISTINCT nr_embargos, ', ') WITHIN GROUP (ORDER BY nr_embargos) AS nr_embargos
-- N     , LISTAGG(DISTINCT valor_executado, ', ') WITHIN GROUP (ORDER BY valor_executado) AS valor_executado
-- N     , LISTAGG(DISTINCT valor_acao, ', ') WITHIN GROUP (ORDER BY valor_acao) AS valor_acao
-- N     , LISTAGG(DISTINCT valor_acordo_agu, ', ') WITHIN GROUP (ORDER BY valor_acordo_agu) AS valor_acordo_agu
-- N     , listagg(distinct nr_precatorio, ', ') WITHIN GROUP (ORDER BY nr_precatorio) AS nr_precatorio
-- N     , listagg(distinct valor_precatorio, ', ') WITHIN GROUP (ORDER BY valor_precatorio) AS valor_precatorio
-- N     , listagg(distinct data_expedicao_precatorio_mask, ', ') WITHIN GROUP (ORDER BY data_expedicao_precatorio_mask) AS data_expedicao_precatorio_mask
-- N     , listagg(distinct nr_suplementar, ', ') WITHIN GROUP (ORDER BY nr_suplementar) AS nr_suplementar
-- N     , listagg(distinct valor_suplementar, ', ') WITHIN GROUP (ORDER BY valor_suplementar) AS valor_suplementar
-- N     , listagg(distinct data_expedicao_suplementar_mask, ', ') WITHIN GROUP (ORDER BY data_expedicao_suplementar_mask) AS data_expedicao_suplementar_mask
-- N     , listagg(distinct valor_devolvido, ', ') WITHIN GROUP (ORDER BY valor_devolvido) AS valor_devolvido
-- N     , listagg(distinct data_devolucao_mask, ', ') WITHIN GROUP (ORDER BY data_devolucao_mask) AS data_devolucao_mask

FROM vw_processo_br p
LEFT JOIN tenant t ON p.tenant_code = t.code
WHERE 1 = 1
GROUP BY p.id, t.name, t.code, nr_processo
ORDER BY nr_processo
/

create view VW_PROCESSOS_COM_MAIS_PARTES as
SELECT DISTINCT nr_processo, partes_cpf
FROM vw_processo_br_grouped
WHERE 1 = 1
    AND partes_cpf > 1
ORDER BY partes_cpf DESC
/

create view VW_PROCESSOS_POR_SITUACAO_FUNCIONAL as
SELECT COUNT(*) total
    , NVL(situacao_funcional, '[INDEFINIDO]') situacao_funcional

FROM (SELECT DISTINCT cpf, situacao_funcional
FROM vw_processo_br)
WHERE 1 = 1
GROUP BY situacao_funcional
ORDER BY total DESC
/

create view VW_JSON_PROCESSO_BR as
SELECT DISTINCT "DUMMY","TENANT_NAME","TENANT_CODE","NR_PROCESSO","PARTES_CPF","AUTOR_ACAO","OBJETO_ACAO","ESCRITORIO_RESPONSAVEL","PARTE_CONTRARIA","VARA_PROCESSO","VARA_CUMPRIMENTO"


FROM vw_processo_br_grouped
WHERE 1 = 1
/

create view VW_PROCESSO_BR_MERGED as
SELECT /*+ RESULT_CACHE */ nr_processo, cpf, autor_acao
FROM (
    SELECT /*+ RESULT_CACHE */ nr_processo, cpf, autor_acao,
           ROW_NUMBER() OVER (PARTITION BY nr_processo ORDER BY cpf) RN
    FROM vw_processo_br
) X
WHERE RN <= 10
/

create FUNCTION mask_br_phone(p_val VARCHAR2)
    RETURN VARCHAR2 DETERMINISTIC IS
BEGIN
    RETURN REGEXP_REPLACE(REGEXP_REPLACE(p_val, '[^0-9]', ''), '^(\d{2})(\d{4,5})(\d{4})$', '(\1) \2-\3');
END;
/

create view VW_RAW_ENTITY as
SELECT e.tenant_id
    , e.tenant_code
    , e.id
    , e.name
    , e.br_cpf
    , e.br_cpf_mask
    , e.birth_date_mask
    , e.br_mobile_mask
    , e.email
    , e.home_uf
    , e.work_uf
    , e.active
    , e.md5_password

FROM entity e
WHERE 1 = 1
/

create view VW_ENTITY as
SELECT "TENANT_ID","TENANT_CODE","ID","NAME","BR_CPF","BR_CPF_MASK","BIRTH_DATE_MASK","BR_MOBILE_MASK","EMAIL","HOME_UF","WORK_UF","ACTIVE","MD5_PASSWORD"

FROM vw_raw_entity
WHERE 1 = 1
        AND LOWER(tenant_code) = LOWER(v('G_TENANT_CODE')) OR SYS_CONTEXT('USERENV', 'MODULE') = 'DataGrip'
/

create view VW_RAW_MEMBER as
SELECT m."ID",m."ID_MEMBRO_OLD",m."ID_PESSOA_OLD",m."ID_PESSOA_EMPRESA_OLD",m."TENANT_CODE",m."TENANT_ID",m."ETYPE_CODE",m."ENTITY_ID",m."ACTIVE",m."MUST_UPDATE",m."IS_DEV",m."CREATED_AT",m."INTERNAL_TAG",m."UPDATED_AT"
    --
    , et.name etype_name
    , et.hash etype_hash
    , et.tag_perfil_old
    --
    , lower(standard_hash(lower(m.tenant_code) || lower(nvl(et.tag_perfil_old, '')) || nvl(e.br_cpf, dbms_random.string('X', 40)), 'SHA1')) br_cpf_hash
    --
    , e.br_cpf
    , e.br_cpf_mask
    , e.name
    , e.email
    , e.br_mobile_mask
    , e.birth_date_mask
    , e.home_uf

FROM member m
LEFT JOIN vw_raw_entity e ON e.id = m.entity_id
LEFT JOIN vw_raw_etype et ON (et.code = m.etype_code AND lower(et.tenant_code) = lower(m.tenant_code))
/

create view VW_MEMBER as
SELECT "ID","ID_MEMBRO_OLD","ID_PESSOA_OLD","ID_PESSOA_EMPRESA_OLD","TENANT_CODE","TENANT_ID","ETYPE_CODE","ENTITY_ID","ACTIVE","MUST_UPDATE","IS_DEV","CREATED_AT","INTERNAL_TAG","UPDATED_AT","ETYPE_NAME","ETYPE_HASH","TAG_PERFIL_OLD","BR_CPF_HASH","BR_CPF","BR_CPF_MASK","NAME","EMAIL","BR_MOBILE_MASK","BIRTH_DATE_MASK","HOME_UF"

FROM vw_raw_member m
WHERE 1 = 1
        AND LOWER(m.tenant_code) = LOWER(v('G_TENANT_CODE')) OR SYS_CONTEXT('USERENV', 'MODULE') = 'DataGrip'
/

create view VW_MEMBROS_POR_ENTIDADE as
SELECT t.code, COUNT(*) total
FROM member m
LEFT JOIN entity e ON m.entity_id = e.id
LEFT JOIN tenant t ON t.code = m.tenant_code
WHERE 1 = 1

    --
    AND m.etype_code = 'associate'
    AND m.active = 1
    AND e.active = 1

    --
    AND m.tenant_code IN
        (SELECT tenant_code FROM mv_partnership_partners WHERE LOWER(parent_code) = LOWER(v('G_TENANT_CODE')))

GROUP BY t.code
ORDER BY COUNT(*) DESC
/

create view VW_MEMBER_PARTNER as
SELECT m."ID",m."ENTITY_ID",m."TENANT_ID",m."TENANT_CODE",m."ETYPE_CODE",m."ACTIVE",m."ID_MEMBRO_OLD",m."ETYPE_NAME",m."ETYPE_HASH",m."TAG_PERFIL_OLD",m."BR_CPF_HASH",m."BR_CPF",m."BR_CPF_MASK",m."NAME",m."EMAIL",m."BR_MOBILE_MASK",m."BIRTH_DATE_MASK",m."HOME_UF"
FROM vw_raw_member m
JOIN partnership p ON p.tenant_code = m.tenant_code
            AND LOWER(p.parent_code) = LOWER(v('G_TENANT_CODE'))
            AND p.role = 'partner'
-- TODO 20250723 rever
-- JOIN role_etype r ON r.etype_code = m.etype_code AND r.role_code = 'partner'
WHERE 1 = 1
/

create FUNCTION only_numbers(p_text VARCHAR2)
    RETURN VARCHAR2
    DETERMINISTIC IS
BEGIN
    RETURN REGEXP_REPLACE(p_text, '[^0-9]', '');
END;
/

create PROCEDURE prc_debug (result IN VARCHAR2, raise IN BOOLEAN DEFAULT false) IS
BEGIN

    --
    dbms_output.put_line(result);

    --
    IF raise THEN
        RAISE_APPLICATION_ERROR(-20001, CHR(10) ||
            '*** prc_raiser *** ' || CHR(10) ||
            '*** sqlerrm *** ' || SQLERRM || CHR(10) ||
            '*** result *** ' || result);
    END IF;

END;
/

create PROCEDURE d (result IN VARCHAR2, raise IN BOOLEAN DEFAULT false) IS
BEGIN

    --
    prc_debug(result, raise);

END;
/

create PROCEDURE dd (result IN VARCHAR2) IS
BEGIN

    --
    prc_debug(result, false);

    -- forca exit
    RAISE_APPLICATION_ERROR(-20000, '[dd EXIT] ' || result);

END;
/

create PROCEDURE dr (result IN VARCHAR2, raise IN BOOLEAN DEFAULT FALSE) IS
BEGIN

    d(chr(10) || '+----------------------------------------+' || CHR(10) || CHR(10) || result || CHR(10) || CHR(10) || '+----------------------------------------+' || CHR(10), raise);

END;
/

create PROCEDURE prc_http_member(p_json IN CLOB) IS
    v_raw    RAW(32767);
    v_req    utl_http.req;
    v_resp   utl_http.resp;
    v_status PLS_INTEGER;
    v_result VARCHAR2(4000);
BEGIN

    -- 20250706 !!
--     dd(p_json);
    v_raw := utl_i18n.string_to_raw(p_json, 'AL32UTF8');

    -- 2) cria requisição POST
    v_req := utl_http.begin_request('https://app.sindicatto.com/entry.php', 'POST', 'HTTP/1.1');
    utl_http.set_header(v_req, 'Content-Type', 'application/json; charset=UTF-8');
    utl_http.set_header(v_req, 'Content-Length', LENGTH(v_raw));
    utl_http.set_header(v_req, 'X-Auth', '6d2a7e54f19c4b0d91c1c187b3c14a7a');
    utl_http.set_body_charset('UTF-8');
    utl_http.write_text(v_req, v_raw);

    -- Recebe resposta
    v_resp := utl_http.get_response(v_req);
    v_status := v_resp.status_code;
    utl_http.read_text(v_resp, v_result);
    utl_http.end_response(v_resp);

    --
    UPDATE member
    SET id_membro_old           = NVL(JSON_VALUE(v_result, '$.id_membro'), id_membro_old)
        , id_pessoa_old         = NVL(JSON_VALUE(v_result, '$.id_pessoa'), id_pessoa_old)
        , id_pessoa_empresa_old = NVL(JSON_VALUE(v_result, '$.id_pessoa_empresa'), id_pessoa_empresa_old)
    WHERE id = JSON_VALUE(p_json, '$.id_member_new');

    -- atualiza ids old entity
    UPDATE entity
    SET id_pessoa_old                 = NVL(JSON_VALUE(v_result, '$.id_pessoa'), id_pessoa_old)
        , id_endereco_residencial_old = NVL(JSON_VALUE(v_result, '$.id_residencial'), id_endereco_residencial_old)
        , id_endereco_comercial_old   = NVL(JSON_VALUE(v_result, '$.id_comercial'), id_endereco_comercial_old)
    WHERE id = JSON_VALUE(p_json, '$.id_entity_new');

    -- restringe debug
    IF SYS_CONTEXT('USERENV', 'MODULE') = 'DataGrip' THEN
        d(123);
        d(p_json);
        d(v_status);
        d(v_result);
    END IF;

-- EXCEPTION
--     WHEN OTHERS THEN
--         RAISE_APPLICATION_ERROR(-20001, 'Erro: ' || SQLERRM || v_result);
END;
/

create PROCEDURE ddr (result IN VARCHAR2, raise IN BOOLEAN DEFAULT FALSE) IS
BEGIN

    --
    dr(result, raise);

    -- forca exit
    RAISE_APPLICATION_ERROR(-20000, '[dd EXIT]');

END;
/

create PROCEDURE prc_http_member_loop(
    p_id_member IN NUMBER DEFAULT NULL,
    p_id_pessoa IN NUMBER DEFAULT NULL,
    p_delete IN    NUMBER DEFAULT 0
) IS
    l_json CLOB;
BEGIN
    SELECT JSON_OBJECT(
            'st_action' VALUE CASE WHEN p_delete = 1 THEN 'DELETE' END,
        --
            'st_time' VALUE SYSTIMESTAMP,
            'st_tenant' VALUE m.tenant_code,
            'id_member_new' VALUE m.id,
            'id_membro' VALUE m.id_membro_old,
            'id_perfil' VALUE t.id_perfil_old,
            'id_pessoa_empresa' VALUE tt.id_pessoa_empresa_old,
            'id_config_father' VALUE tt.id_config_father_old,
        --
            'id_entity_new' VALUE e.id,
            'id_pessoa' VALUE e.id_pessoa_old,
            'id_endereco_residencial' VALUE e.id_endereco_residencial_old,
            'id_endereco_comercial' VALUE e.id_endereco_comercial_old,
        --
            'st_tag_uf_residencial' VALUE e.home_uf,
            'st_tag_uf_comercial' VALUE e.work_uf,
        --
            'st_cpf' VALUE e.br_cpf,
            'st_nome' VALUE e.name,
            'st_email' VALUE e.email,
            'dt_nascimento' VALUE TO_CHAR(birth_date, 'YYYY-MM-DD'),
            'st_celular' VALUE e.br_mobile
           )
    INTO l_json
    FROM member m
    LEFT JOIN tenant tt ON tt.code = m.tenant_code
    LEFT JOIN entity e ON m.entity_id = e.id
    LEFT JOIN etype t ON t.code = m.etype_code AND t.tenant_code = m.tenant_code
    WHERE 1 = 1
        AND (p_id_member IS NULL OR m.id = p_id_member)
        AND (p_id_pessoa IS NULL OR e.id_pessoa_old = p_id_pessoa);

    --
    prc_http_member(l_json);

END;
/

create FUNCTION is_cpf_valid(p_cpf IN VARCHAR2) RETURN BOOLEAN IS
    v_cpf VARCHAR2(11);
    soma1 NUMBER := 0;
    soma2 NUMBER := 0;
    dig1  NUMBER;
    dig2  NUMBER;
BEGIN
    -- remove pontuação
    v_cpf := REGEXP_REPLACE(p_cpf, '[^0-9]', '');

    -- valida tamanho
    IF LENGTH(v_cpf) != 11 THEN
        RETURN FALSE;
    END IF;

    -- elimina CPFs inválidos com dígitos repetidos
    IF v_cpf IN (
                 '00000000000', '11111111111', '22222222222', '33333333333', '44444444444',
                 '55555555555', '66666666666', '77777777777', '88888888888', '99999999999'
        ) THEN
        RETURN FALSE;
    END IF;

    -- calcula 1º dígito verificador
    FOR i IN 1 .. 9 LOOP
        soma1 := soma1 + TO_NUMBER(SUBSTR(v_cpf, i, 1)) * (10 - i);
    END LOOP;
    dig1 := 11 - MOD(soma1, 11);
    IF dig1 >= 10 THEN dig1 := 0;
    END IF;

    -- calcula 2º dígito verificador
    FOR i IN 1 .. 9 LOOP
        soma2 := soma2 + TO_NUMBER(SUBSTR(v_cpf, i, 1)) * (11 - i);
    END LOOP;
    soma2 := soma2 + dig1 * 2;
    dig2 := 11 - MOD(soma2, 11);
    IF dig2 >= 10 THEN dig2 := 0;
    END IF;

    -- compara com os dígitos do CPF
    RETURN dig1 = TO_NUMBER(SUBSTR(v_cpf, 10, 1)) AND
        dig2 = TO_NUMBER(SUBSTR(v_cpf, 11, 1));
END;
/

create FUNCTION etype_is_read_only (
    p_member_id IN NUMBER DEFAULT NULL
) RETURN BOOLEAN IS
    v_read_only NUMBER(1);
BEGIN

    -- pega se é read_only
    SELECT t.read_only
    INTO v_read_only
    FROM member m
    LEFT JOIN etype t ON t.code = m.etype_code
    WHERE 1 = 1
        AND m.id = p_member_id
        AND NVL(t.read_only, 0) = 1;

    RETURN TRUE;

EXCEPTION
    WHEN no_data_found THEN
        RETURN FALSE;

END;
/

create FUNCTION etype_is_admin (
    p_member_id IN NUMBER DEFAULT NULL
) RETURN BOOLEAN IS
    v_read_only NUMBER(1);
BEGIN

    -- pega se é read_only
    SELECT t.read_only
    INTO v_read_only
    FROM member m
    LEFT JOIN etype t ON t.code = m.etype_code
    WHERE 1 = 1
        AND m.id = p_member_id
        AND t.is_admin = 1;

    RETURN TRUE;

EXCEPTION
    WHEN no_data_found THEN
        RETURN FALSE;

END;
/

create FUNCTION get_email_tenant (
    p_tenant_code IN VARCHAR2 DEFAULT NULL
) RETURN STRING IS
    v_email VARCHAR2(255);
BEGIN

    --
    SELECT email
    INTO v_email
    FROM tenant
    WHERE LOWER(code) = LOWER(p_tenant_code);

    --
    RETURN v_email;

END;
/

create PROCEDURE prc_http_mail(
    p_subject IN VARCHAR2,
    p_body IN VARCHAR2,
    p_start_date IN DATE DEFAULT NULL,
    p_end_date IN DATE DEFAULT NULL,
    p_testing IN NUMBER DEFAULT 0
) IS

    --
    v_req utl_http.req;
    v_resp utl_http.resp;
    v_result VARCHAR2(4000) := '[sem resposta]';
    v_status PLS_INTEGER;
    v_raw    RAW(32767);
    v_json VARCHAR2(4000);

BEGIN

    --
    v_json := JSON_OBJECT(
            'st_tenant_email' VALUE get_email_tenant(NVL('', '...'))
        , 'st_entity_name' VALUE NVL('', 'phpstorm console')
        , 'nr_testing' VALUE p_testing
        , 'tenantCode' VALUE NVL('', '...')
        , 'tenantName' VALUE NVL('', '...')
        , 'subject' VALUE p_subject
        , 'body' VALUE p_body
        , 'start_date' VALUE CASE WHEN p_start_date IS NOT NULL THEN TO_CHAR(p_start_date, 'YYYY-MM-DD') END
        , 'end_date' VALUE CASE WHEN p_end_date IS NOT NULL THEN TO_CHAR(p_end_date, 'YYYY-MM-DD') END
              );

    --
    v_raw := utl_i18n.string_to_raw(v_json, 'AL32UTF8');
    v_req := utl_http.begin_request('https://app.sindicatto.com/email.php', 'POST', 'HTTP/1.1');
    utl_http.set_header(v_req, 'Content-Type', 'application/json; charset=UTF-8');
    utl_http.set_header(v_req, 'Content-Length', LENGTH(v_raw));
    utl_http.set_header(v_req, 'X-Auth', '6d2a7e54f19c4b0d91c1c187b3c14a7a');
    utl_http.write_text(v_req, v_raw);

    -- Recebe resposta+

    v_resp := utl_http.get_response(v_req);
    v_status := v_resp.status_code;
    utl_http.read_text(v_resp, v_result);
    utl_http.end_response(v_resp);

    -- restringe debug
    IF SYS_CONTEXT('USERENV', 'MODULE') = 'DataGrip' THEN
        d(v_raw);
        d(v_status);
        d(v_result);
    END IF;

    -- EXCEPTION
    --     WHEN OTHERS THEN
    --         RAISE_APPLICATION_ERROR(-20001, 'Atenção: ' || SQLERRM);
END;
/

create PROCEDURE prc_http_voucher_cancel(p_codigo IN VARCHAR2, p_force IN PLS_INTEGER) IS
    v_req    utl_http.req;
    v_resp   utl_http.resp;
    v_result VARCHAR2(4000) := '[sem resposta]';
    v_body   VARCHAR2(4000);
    v_status PLS_INTEGER;
BEGIN

    -- 1) cria json
    v_body := '{"action":"update", "codigo":"' || p_codigo || '", "force": ' || p_force || '}';

    -- 2) cria requisição POST
    v_req := utl_http.begin_request(
            'https://app.sindicatto.com/post.php',
            'POST',
            'HTTP/1.1'
             );

    -- Headers obrigatórios
    utl_http.set_header(v_req, 'Content-Type', 'application/json');
    utl_http.set_header(v_req, 'Content-Length', LENGTH(v_body));
    utl_http.set_header(v_req, 'X-Auth', '6d2a7e54f19c4b0d91c1c187b3c14a7a');

    -- Envia JSON no corpo
    utl_http.write_text(v_req, v_body);

    -- Recebe resposta
    v_resp := utl_http.get_response(v_req);
    v_status := v_resp.status_code;
    utl_http.read_text(v_resp, v_result);
    utl_http.end_response(v_resp);

    -- restringe debug
    IF SYS_CONTEXT('USERENV', 'MODULE') = 'DataGrip' THEN
        d(v_body);
        d(v_status);
        d(v_result);
    END IF;

    --
    IF v_status = 200 THEN
        prc_http_mail('Voucher ' || p_codigo || ' cancelado por ' || NVL(v('G_ENTITY_NAME'), '[terminal]'), NVL(JSON_VALUE(v_result, '$.mensagem'), 'Consulte mais detalhes no sistema.'));
    ELSE
        RAISE_APPLICATION_ERROR(-20001, '❌' || v_status || ': ' || JSON_VALUE(v_result, '$.mensagem'));
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Atenção: ' || SQLERRM);
END;
/

create FUNCTION permission2 (
    p_tenant_code IN VARCHAR2 DEFAULT NULL,
    p_member_id IN NUMBER DEFAULT NULL,
    p_what IN VARCHAR2 DEFAULT NULL,
    p_value IN VARCHAR2 DEFAULT NULL
) RETURN BOOLEAN IS
    v_result      NUMBER;
    v_tenant_code VARCHAR2(50);
    v_etype_code  VARCHAR2(20);
BEGIN

    RETURN FALSE;

END;
/

create FUNCTION tenant_has_partners RETURN NUMBER IS

    v_count NUMBER;

BEGIN

    -- verifica se o tenant possui parceiros
    SELECT COUNT(*)
    INTO v_count
    FROM mv_partnership_partners
    WHERE parent_code = v('G_TENANT_CODE');

    --
    d(v_count);
    RETURN v_count;

    --
EXCEPTION
    WHEN no_data_found THEN
        RETURN NULL;

END;
/

create FUNCTION tenant_has_lawsuits RETURN NUMBER IS

    v_count NUMBER;

BEGIN

    -- verifica se o tenant possui parceiros
    SELECT COUNT(*)
    INTO v_count
    FROM vw_processo_br_grouped
    WHERE 1
        -- TODO 20250722 fixo anp
        AND LOWER(v('G_TENANT_CODE')) = 'anpprev';

    --
    d(v_count);
    RETURN v_count;

    --
EXCEPTION
    WHEN no_data_found THEN
        RETURN NULL;

END;
/

create PROCEDURE prc_set_tenant (p_tenant_code IN varchar2, p_cpf_hash IN varchar2 DEFAULT NULL) AS
    v_tid number;
    v_cookie owa_cookie.COOKIE;
    v_tenant_code varchar2(100);
    v_tenant_name varchar2(100);
BEGIN

    -- 1) ID Tenant por parametro? Prioritario
    IF (p_tenant_code IS NOT NULL) THEN
        owa_cookie.remove('COOKIE_TENANT_ID', v_tid, '/ords');
        SELECT id INTO v_tid FROM tenant WHERE lower(code) = lower(p_tenant_code);
    END IF;

    -- 2) ID Tenant por cookie?
    -- se v_tid for nulo, tenta pegar v_cookie - NAO RODA NO CONSOLE/DATAGRIP
    v_cookie := owa_cookie.get('COOKIE_TENANT_ID');
    IF v_tid IS NULL AND v_cookie.vals.count > 0 THEN
        v_tid := v_cookie.vals(1);
    END IF;

    -- 3) Nao tem cookie nem param, pega default
    IF v_tid IS NULL THEN
        SELECT id INTO v_tid FROM tenant WHERE lower(code) = 'sindicatto';
    END IF;

    -- seta v_cookie com o v_tid atual - path /ords é parte da chave do cookie (Ver F12 - 20250626)
    owa_cookie.send('COOKIE_TENANT_ID', v_tid, NULL, '/ords');

    -- busca do banco
    BEGIN

        --
        SELECT id, code, name INTO v_tid, v_tenant_code, v_tenant_name FROM tenant WHERE id = v_tid;

        -- 20250703 login cpf
        IF (p_cpf_hash IS NOT NULL) THEN
            prc_set_member_by_hash(v_tenant_code, p_cpf_hash);
        END IF;

        --
        apex_util.set_session_state('G_TENANT_ID', v_tid);
        apex_util.set_session_state('G_TENANT_CODE', v_tenant_code);
        apex_util.set_session_state('G_TENANT_CODE_LOWER', lower(v_tenant_code));
        apex_util.set_session_state('G_TENANT_NAME', v_tenant_name);

    EXCEPTION
        WHEN no_data_found THEN
            raise_application_error(-20001, 'Invalid tenant.');
    END;

END;
/

create PROCEDURE prc_log_login (
    p_user IN        VARCHAR2,
    p_tenant_code IN VARCHAR2,
    p_entity_id IN   NUMBER DEFAULT NULL,
    p_etype_code IN  VARCHAR2,
    p_member_id IN   NUMBER DEFAULT NULL,
    p_success IN     NUMBER,
    p_error_code IN  VARCHAR2,
    p_sql_error IN   VARCHAR2 DEFAULT NULL
) IS
BEGIN
    INSERT INTO login_log (
        login_user, tenant_code, etype_code, success, error_code, ip_address, user_agent, entity_id, member_id, sql_error
    )
    VALUES (
        p_user, p_tenant_code, p_etype_code, p_success, p_error_code, owa_util.get_cgi_env('REMOTE_ADDR'), owa_util.get_cgi_env('HTTP_USER_AGENT'), p_entity_id, p_member_id, p_sql_error
    );
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('Log failed: ' || SQLERRM);
END;
/

create PROCEDURE prc_internal_login (
    p_tenant_code IN varchar2
, p_user IN varchar2
, p_pass IN varchar2
, p_etype_code IN varchar2 DEFAULT NULL
, p_entity_id OUT number
) IS

    v_member_id number;
    v_entity_name varchar2(200);
    v_etype_name varchar2(100);

BEGIN

    --
    SELECT m.id, t.name, e.id, e.name
    INTO v_member_id, v_etype_name, p_entity_id, v_entity_name
    FROM vw_raw_member m
    JOIN vw_raw_entity e ON e.id = m.entity_id
    JOIN vw_raw_etype t ON t.code = m.etype_code
    WHERE 1 = 1
        AND m.active = 1
        AND e.active = 1
        AND (lower(e.br_cpf) = lower(p_user) OR lower(e.email) = lower(p_user))
        AND (p_etype_code IS NULL OR lower(m.etype_code) = lower(p_etype_code))
        AND (lower(e.md5_password) = lower(standard_hash(p_pass, 'MD5')))
        AND lower(m.tenant_code) = lower(p_tenant_code)
    ORDER BY m.id DESC FETCH FIRST 1 ROW ONLY;

    -- so define sessao se passou o login completo com etype_code
    IF (p_etype_code IS NOT NULL) THEN
        --
        apex_util.set_session_state('G_MEMBER_ID', v_member_id);
        apex_util.set_session_state('G_ENTITY_NAME', v_entity_name);
        apex_util.set_session_state('G_ETYPE_NAME', v_etype_name);
        apex_util.set_session_state('G_ETYPE_CODE', p_etype_code);

        -- sucesso com tipo
        prc_log_login(p_user, p_tenant_code, p_entity_id, p_etype_code, v_member_id, 1, '', NULL);


    ELSE

        -- sucesso sem tipo
        prc_log_login(p_user, p_tenant_code, p_entity_id, p_etype_code, NULL, 2, '', NULL);

    END IF;

EXCEPTION
    WHEN no_data_found THEN
        prc_log_login(p_user, p_tenant_code, NULL, p_etype_code, NULL, 0, 'no_data_found', sqlerrm);
        raise_application_error(-20002, 'Login inválido [NDF0].');

    WHEN too_many_rows THEN
        prc_log_login(p_user, p_tenant_code, NULL, p_etype_code, NULL, 0, 'too_many_rows', sqlerrm);
        raise_application_error(-20003, 'Login inválido [TMR+].');

    --     WHEN OTHERS THEN
    --         prc_log_login(p_user, p_tenant_code, NULL, p_etype_code, NULL, 0, 'others', SQLERRM);
    --         RAISE_APPLICATION_ERROR(-20003, 'Login inválido [OTH?].');

END;
/

create PROCEDURE prc_internal_login_etype_count (
    p_tenant_code IN VARCHAR2,
    p_user IN        VARCHAR2,
    p_pass IN        VARCHAR2
) IS

    v_total NUMBER;

BEGIN

    -- total de etypes do membro
    SELECT COUNT(*)
    INTO v_total
    FROM member m
    JOIN entity e ON e.id = m.entity_id
    JOIN etype t ON t.code = m.etype_code
    WHERE 1 = 1
        AND m.active = 1
        AND e.active = 1
        AND (e.br_cpf = p_user OR e.email = p_user)
        AND (e.md5_password = standard_hash(p_pass, 'MD5'))
        AND LOWER(m.tenant_code) = LOWER(p_tenant_code);

    RETURN v_total;

END;
/

create FUNCTION members_etypes_count (
    p_tenant_code IN varchar2
, p_user IN varchar2
, p_pass IN varchar2
) RETURN varchar2 IS

    v_etype_code varchar2(100);
    v_total number;

BEGIN

    --
    SELECT count(*), max(m.etype_code)
    INTO v_total, v_etype_code
    FROM member m
    JOIN entity e ON e.id = m.entity_id
    WHERE 1 = 1
        AND m.active = 1
        AND e.active = 1
        AND (e.br_cpf = p_user OR e.email = p_user)
        AND e.md5_password = lower(standard_hash(p_pass, 'MD5'))
        AND lower(m.tenant_code) = lower(p_tenant_code);

    IF v_total = 1 THEN
        RETURN v_etype_code;
    ELSE
        RETURN NULL;
    END IF;

END;
/

create FUNCTION json_member(
    p_id_member IN        NUMBER DEFAULT NULL,
    p_id_pessoa IN        NUMBER DEFAULT NULL,
    p_delete IN           NUMBER DEFAULT 0,
    p_new_password_md5 IN VARCHAR2 DEFAULT NULL
) RETURN CLOB IS
    l_json CLOB;
BEGIN
    SELECT JSON_OBJECT(
            'st_action' VALUE CASE WHEN p_delete = 1 THEN 'DELETE' END,
        --
            'st_time' VALUE SYSTIMESTAMP,
            'st_tenant' VALUE m.tenant_code,
            'id_member_new' VALUE m.id,
            'id_membro' VALUE m.id_membro_old,
            'id_perfil' VALUE t.id_perfil_old,
            'id_pessoa_empresa' VALUE tt.id_pessoa_empresa_old,
            'id_config_father' VALUE tt.id_config_father_old,
        --
            'id_entity_new' VALUE e.id,
            'id_entity' VALUE e.id,
            'id_pessoa' VALUE e.id_pessoa_old,
            'id_endereco_residencial' VALUE e.id_endereco_residencial_old,
            'id_endereco_comercial' VALUE e.id_endereco_comercial_old,
        --
            'st_tag_uf_residencial' VALUE e.home_uf,
            'st_tag_uf_comercial' VALUE e.work_uf,
        --
            'st_cpf' VALUE e.br_cpf,
            'st_nome' VALUE e.name,
            'st_email' VALUE e.email,
            'dt_nascimento' VALUE TO_CHAR(birth_date, 'YYYY-MM-DD'),
            'st_celular' VALUE e.br_mobile,
            'st_new_password_md5' VALUE p_new_password_md5
           )
    INTO l_json
    FROM member m
    LEFT JOIN tenant tt ON tt.code = m.tenant_code
    LEFT JOIN entity e ON m.entity_id = e.id
    LEFT JOIN etype t ON t.code = m.etype_code AND t.tenant_code = m.tenant_code
    WHERE 1 = 1
        AND (p_id_member IS NULL OR m.id = p_id_member)
        AND (p_id_pessoa IS NULL OR e.id_pessoa_old = p_id_pessoa);

    --
    RETURN l_json;

END;
/

create PROCEDURE prc_http_entity_pwchange(p_json IN CLOB) IS
    v_raw          RAW(32767);
    v_req          utl_http.req;
    v_resp         utl_http.resp;
    v_status       PLS_INTEGER;
    v_result       VARCHAR2(4000);
    --
    v_password_md5 VARCHAR2(32);
    v_id_entity    NUMBER;

BEGIN

    --
    v_raw := utl_i18n.string_to_raw(p_json, 'AL32UTF8');

    -- 2) cria requisição POST
    v_req := utl_http.begin_request('https://app.sindicatto.com/http_entity_pwchange.php', 'POST', 'HTTP/1.1');
    utl_http.set_header(v_req, 'Content-Type', 'application/json; charset=UTF-8');
    utl_http.set_header(v_req, 'Content-Length', LENGTH(v_raw));
    utl_http.set_header(v_req, 'X-Auth', '6d2a7e54f19c4b0d91c1c187b3c14a7a');
    utl_http.set_body_charset('UTF-8');
    utl_http.write_text(v_req, v_raw);

    -- Recebe resposta
    v_resp := utl_http.get_response(v_req);
    v_status := v_resp.status_code;
    utl_http.read_text(v_resp, v_result);
    utl_http.end_response(v_resp);

    -- atualiza senha oracle
    BEGIN
        SELECT JSON_VALUE(p_json, '$.st_new_password_md5'), JSON_VALUE(p_json, '$.id_entity') INTO v_password_md5, v_id_entity FROM dual;
        UPDATE entity SET md5_password = lower(v_password_md5) WHERE id = v_id_entity;
    EXCEPTION
        WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20002, 'Erro ao atualizar senha: ' || SQLERRM);
    END;


    -- restringe debug
    IF SYS_CONTEXT('USERENV', 'MODULE') = 'DataGrip' THEN
        d(p_json);
        d(v_status);
        d(v_result);
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Erro: ' || SQLERRM || v_result);
END;
/

create FUNCTION is_sindicatto
    RETURN BOOLEAN IS
BEGIN

    IF (LOWER(v('G_TENANT_CODE')) = 'sindicatto') THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;

END;
/

create view VW_CONTENT as
SELECT c.id,
       c.tenant_code,
       c.ctype_code,
       c.subtype,
       c.contents,
       c.title,
       c.created_at,
       c.updated_at,
       c.published_at,
       c.image_blob,
       c.image_mime_type,
       c.image_filename,
       c.image_alt,
       c.image_url,
       c.image_updated_at,
       c.content_format,
       c.slug,
       c.sort_order,
       c.status,
       c.author_name,
       c.source_name,
       c.source_url,
       CASE
           WHEN c.ctype_code = 'news' AND c.subtype = 'latest-reports' THEN 'Informe'
           WHEN c.ctype_code = 'news' AND c.subtype = 'multimedia' THEN 'Fotos e Vídeos'
           WHEN c.ctype_code = 'news' THEN 'Notícia'
           ELSE ct.name
       END AS ctype_name
  FROM content c
  LEFT JOIN ctype ct
    ON ct.code = c.ctype_code
 WHERE 1 = 1
   AND (
       LOWER(c.tenant_code) = LOWER(v('G_TENANT_CODE'))
       OR SYS_CONTEXT('USERENV', 'MODULE') = 'DataGrip'
       OR is_sindicatto()
   )
 ORDER BY CASE WHEN c.ctype_code = 'news' THEN 0 ELSE 1 END,
          c.ctype_code,
          c.subtype,
          c.id DESC
/

create FUNCTION get_current_page_alias RETURN varchar2 IS

    l_page_alias varchar2(100);

BEGIN

    SELECT lower(page_alias)
    INTO l_page_alias
    FROM apex_application_pages
    WHERE application_id = to_number(v('APP_ID'))
        AND page_id = to_number(v('APP_PAGE_ID'));

    --
    RETURN l_page_alias;

EXCEPTION
    WHEN no_data_found THEN
        RETURN lower(v('APP_PAGE_ID'));
END;
/

create FUNCTION has_permission (
    p_action_code IN varchar2
, p_page_alias IN varchar2 DEFAULT NULL
, p_actor_etype_code IN varchar2 DEFAULT NULL
, p_target_etype_code IN varchar2 DEFAULT NULL
, p_tenant_code IN varchar2 DEFAULT NULL
, p_is_dev IN number DEFAULT NULL
) RETURN boolean IS

    l_tenant_code varchar2(50);
    l_actor_etype_code varchar2(100);
    l_target_etype_code varchar2(100);
    l_page_alias varchar2(100);
    l_action_code varchar2(50);
    l_is_dev number;
    l_count number;

BEGIN

    --
    l_tenant_code := lower(coalesce(p_tenant_code, v('G_TENANT_CODE')));
--     IF l_tenant_code = 'sindicatto' THEN RETURN TRUE; END IF;

    --
    l_actor_etype_code := lower(coalesce(p_actor_etype_code, v('G_ETYPE_CODE')));
    l_target_etype_code := lower(p_target_etype_code);
    l_page_alias := lower(coalesce(p_page_alias, get_current_page_alias));
    l_action_code := lower(p_action_code);
    l_is_dev := nvl(p_is_dev, nvl(to_number(v('G_IS_DEV')), 0));

    --
    IF l_tenant_code IS NULL
        OR l_actor_etype_code IS NULL
        OR l_page_alias IS NULL
        OR l_action_code IS NULL
    THEN
        RETURN FALSE;
    END IF;

    --
    SELECT count(*)
    INTO l_count
    FROM tenant_permission tp
    JOIN etype etype_actor ON lower(etype_actor.tenant_code) = lower(tp.tenant_code) AND lower(etype_actor.code) = l_actor_etype_code
    LEFT JOIN etype etype_target ON lower(etype_target.tenant_code) = lower(tp.tenant_code) AND lower(etype_target.code) = l_target_etype_code
    JOIN etype_permission ep ON lower(ep.tenant_code) = lower(tp.tenant_code) AND lower(ep.page_alias) = lower(tp.page_alias) AND lower(ep.etype_code) = lower(etype_actor.code)
    WHERE lower(tp.tenant_code) = l_tenant_code
        AND lower(tp.page_alias) = l_page_alias
        AND lower(ep.action_code) = l_action_code
        AND (nvl(etype_actor.active, 0) = 1)
        AND (nvl(ep.requires_dev, 0) = 0 OR l_is_dev = 1)
        AND (nvl(ep.active, 0) = 1)
        AND (
        l_target_etype_code IS NULL
            OR (etype_target.id IS NOT NULL
            AND nvl(etype_target.active, 0) = 1
            )
        );

    --
    RETURN l_count > 0;

EXCEPTION
    WHEN OTHERS THEN
        RETURN FALSE;
END;
/

