
-- Generated by ORDS REST Data Services 26.2.0.r1732140
-- Schema: WKSP_SINDICATTO  Date: Wed Jul 08 08:07:49 2026 
--
        
DECLARE

  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'wksp_sindicatto',
      p_auto_rest_auth      => FALSE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'public',
      p_base_path      => '/public/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'public',
      p_pattern        => 'news',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'public',
      p_pattern        => 'news',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT c.id
     , c.tenant_code
     , c.ctype_code
     , c.slug
     , c.sort_order
     , c.status
     , c.title
     , c.contents
     , c.content_format
     , c.author_name
     , c.source_name
     , c.source_url
     , c.created_at
     , c.updated_at
     , c.published_at
     , c.image_alt
     , c.image_filename
     , CASE
           WHEN c.image_url IS NOT NULL THEN
               c.image_url
           WHEN c.image_blob IS NOT NULL THEN
               ''/ords/wksp_sindicatto/public/content-image/'' || c.id ||
               ''?v='' || to_char(nvl(c.image_updated_at, c.updated_at), ''YYYYMMDDHH24MISS'')
       END AS image_url
     , ct.name AS ctype_name
FROM content c
LEFT JOIN ctype ct
       ON lower(ct.tenant_code) = lower(c.tenant_code)
      AND lower(ct.code) = lower(c.ctype_code)
WHERE lower(c.ctype_code) = ''news''
  AND (:tenant_code IS NULL OR lower(c.tenant_code) = lower(:tenant_code))
  AND nvl(c.status, ''published'') = ''published''
OR' || 'DER BY c.published_at DESC, c.id DESC
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'public',
      p_pattern            => 'news',
      p_method             => 'GET',
      p_name               => 'tenant_code',
      p_bind_variable_name => 'tenant_code',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'public',
      p_pattern        => 'content-attachments/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'public',
      p_pattern        => 'content-attachments/:id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT a.id
     , a.content_id
     , a.sort_order
     , a.title
     , a.file_url
     , a.file_name
     , a.mime_type
     , a.file_size_bytes
     , a.is_external
     , a.created_at
     , a.updated_at
FROM content_attachment a
JOIN content c
  ON c.id = a.content_id
WHERE a.content_id = :id
  AND nvl(c.status, ''published'') = ''published''
ORDER BY nvl(a.sort_order, 999999), a.id
');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'public',
      p_pattern        => 'news/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'public',
      p_pattern        => 'news/:id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT c.id
     , c.tenant_code
     , c.ctype_code
     , c.slug
     , c.sort_order
     , c.status
     , c.title
     , c.contents
     , c.content_format
     , c.author_name
     , c.source_name
     , c.source_url
     , c.created_at
     , c.updated_at
     , c.published_at
     , c.image_alt
     , c.image_filename
     , CASE
           WHEN c.image_url IS NOT NULL THEN
               c.image_url
           WHEN c.image_blob IS NOT NULL THEN
               ''/ords/wksp_sindicatto/public/content-image/'' || c.id ||
               ''?v='' || to_char(nvl(c.image_updated_at, c.updated_at), ''YYYYMMDDHH24MISS'')
       END AS image_url
     , ct.name AS ctype_name
FROM content c
LEFT JOIN ctype ct
       ON lower(ct.tenant_code) = lower(c.tenant_code)
      AND lower(ct.code) = lower(c.ctype_code)
WHERE c.id = :id
  AND (:tenant_code IS NULL OR lower(c.tenant_code) = lower(:tenant_code))
  AND nvl(c.status, ''published'') = ''published''
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'public',
      p_pattern            => 'news/:id',
      p_method             => 'GET',
      p_name               => 'tenant_code',
      p_bind_variable_name => 'tenant_code',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'public',
      p_pattern        => 'contents/:code',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'public',
      p_pattern        => 'contents/:code',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT c.id
     , c.tenant_code
     , c.ctype_code
     , c.slug
     , c.sort_order
     , c.status
     , c.title
     , c.contents
     , c.content_format
     , c.author_name
     , c.source_name
     , c.source_url
     , c.created_at
     , c.updated_at
     , c.published_at
     , c.image_alt
     , c.image_filename
     , CASE
           WHEN c.image_url IS NOT NULL THEN
               c.image_url
           WHEN c.image_blob IS NOT NULL THEN
               ''/ords/wksp_sindicatto/public/content-image/'' || c.id ||
               ''?v='' || to_char(nvl(c.image_updated_at, c.updated_at), ''YYYYMMDDHH24MISS'')
       END AS image_url
     , ct.name AS ctype_name
FROM content c
LEFT JOIN ctype ct
       ON lower(ct.tenant_code) = lower(c.tenant_code)
      AND lower(ct.code) = lower(c.ctype_code)
WHERE lower(c.ctype_code) = lower(:code)
  AND (:tenant_code IS NULL OR lower(c.tenant_code) = lower(:tenant_code))
  AND nvl(c.status, ''published'') = ''publishe' || 'd''
ORDER BY nvl(c.sort_order, 999999), c.published_at DESC, c.id DESC
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'public',
      p_pattern            => 'contents/:code',
      p_method             => 'GET',
      p_name               => 'tenant_code',
      p_bind_variable_name => 'tenant_code',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'public',
      p_pattern        => 'content-image/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'public',
      p_pattern        => 'content-image/:id',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT nvl(image_mime_type, ''image/jpeg'') AS content_type
    , image_blob AS content
FROM content
WHERE id = :id
    AND image_blob IS NOT NULL
    AND nvl(status, ''published'') = ''published''
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'public',
      p_pattern            => 'content-image/:id',
      p_method             => 'GET',
      p_name               => 'tenant_code',
      p_bind_variable_name => 'tenant_code',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;

END;