CREATE TABLE workspace_recipient_recent
(
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code     VARCHAR2(50) NOT NULL,
    member_id       NUMBER NOT NULL,

    recipient_type  VARCHAR2(30) NOT NULL,
    recipient_id    NUMBER,
    recipient_name  VARCHAR2(300),
    recipient_value VARCHAR2(500) NOT NULL,

    source_type     VARCHAR2(50),
    last_used_at    DATE DEFAULT SYSDATE NOT NULL,
    use_count       NUMBER DEFAULT 1 NOT NULL,

    created_at      DATE DEFAULT SYSDATE NOT NULL,
    updated_at      DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT ck_workspace_recipient_type
        CHECK (recipient_type IN (
                                  'member',
                                  'email',
                                  'phone',
                                  'external'
            )),

    CONSTRAINT uk_workspace_recipient_recent
        UNIQUE (
                tenant_code,
                member_id,
                recipient_type,
                recipient_value
            ),

    CONSTRAINT fk_workspace_recent_member
        FOREIGN KEY (member_id) REFERENCES member(id)
);