UPDATE TENANT
SET
    BRAND_PRIMARY_COLOR   = '#B5122B',
    BRAND_SECONDARY_COLOR = '#123C6C',
    BRAND_ACCENT_COLOR    = '#E30613',
    UPDATED_AT             = SYSDATE
WHERE LOWER(TRIM(CODE)) = 'anpprev';

COMMIT;


SELECT
    CODE,
    NAME,
    BRAND_PRIMARY_COLOR,
    BRAND_SECONDARY_COLOR,
    BRAND_ACCENT_COLOR,
    UPDATED_AT
FROM TENANT
WHERE LOWER(TRIM(CODE)) = 'anpprev';