CREATE TABLE workspace_notification
(
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code     VARCHAR2(50) NOT NULL,
    entity_id       NUMBER NOT NULL,
    notification_type VARCHAR2(50) NOT NULL,
    title           VARCHAR2(300) NOT NULL,
    message         VARCHAR2(2000),
    reference_type  VARCHAR2(50),
    reference_id    NUMBER,
    read_at         DATE,
    created_at      DATE DEFAULT SYSDATE NOT NULL
);