CREATE UNIQUE INDEX UK_MEMBER_TENANT_MEMBRO_OLD
    ON MEMBER (
               CASE WHEN ID_MEMBRO_OLD IS NOT NULL THEN TENANT_CODE END,
               CASE WHEN ID_MEMBRO_OLD IS NOT NULL THEN ID_MEMBRO_OLD END
        );