DROP TABLE address CASCADE CONSTRAINTS;
CREATE TABLE address
(
    id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    --
    tenant_code     VARCHAR2(50) NOT NULL,
    tenant_id       INTEGER,
    entity_id       INTEGER,
    --
    id_endereco_old INTEGER,
    id_pessoa_old   INTEGER,
    --
    type            VARCHAR2(20),
    uf              VARCHAR2(2),
    street          VARCHAR2(255),

    --
    CONSTRAINT ck_address_uf CHECK (uf IS NULL OR REGEXP_LIKE(uf, '^[A-Z]{2}$')),

    --
    CONSTRAINT fk_address_entity FOREIGN KEY (entity_id) REFERENCES entity(id),
    CONSTRAINT fk_address_tenant FOREIGN KEY (tenant_id) REFERENCES tenant(id)
);

SELECT * FROM address;