DROP TABLE login_log;

CREATE TABLE login_log (
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    member_id   NUMBER,        -- se identificado
    entity_id   NUMBER,        -- se identificado
    login_user  VARCHAR2(255), -- CPF ou e-mail informado
    tenant_code VARCHAR2(100),
    etype_code  VARCHAR2(50),
    success     NUMBER(1),     -- 1 = sucesso, 0 = falha
    error_code  VARCHAR2(20),  -- código de erro opcional
    ip_address  VARCHAR2(45),
    sql_error   VARCHAR2(4000),
    user_agent  VARCHAR2(4000),
    created_at  DATE DEFAULT SYSDATE
);

SELECT * FROM login_log;
