DROP TABLE processo_br CASCADE CONSTRAINTS;
CREATE TABLE processo_br (
    id                              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    tenant_code                     VARCHAR2(50), -- pode ser null pq é importada sem tenant
    -- partes
    nome                            VARCHAR2(500),
    cpf                             VARCHAR2(100),
    cpf_mask                        VARCHAR2(20) GENERATED ALWAYS AS (CAST(mask_br_cpf(cpf) AS VARCHAR2(20))) VIRTUAL,
    situacao_funcional              VARCHAR2(100),
    nome_pensionista                VARCHAR2(150),
    cpf_pensionista                 VARCHAR2(100),
    cpf_pensionista_mask            VARCHAR2(20) GENERATED ALWAYS AS (CAST(mask_br_cpf(cpf_pensionista) AS VARCHAR2(20))) VIRTUAL,

    -- ação
    autor_acao                      VARCHAR2(150),
    objeto_acao                     VARCHAR2(200),
    escritorio_responsavel          VARCHAR2(150),
    parte_contraria                 VARCHAR2(150),

    -- processos
    nr_processo                     VARCHAR2(100),
    vara_processo                   VARCHAR2(150),
    nr_cumprimento                  VARCHAR2(100),
    nr_embargos                     VARCHAR2(100),
    vara_cumprimento                VARCHAR2(150),

    -- valores
    valor_executado                 NUMBER(18, 2),
    valor_acao                      NUMBER(18, 2),
    valor_acordo_agu                NUMBER(18, 2),

    -- precatório / rpv
    nr_precatorio                   VARCHAR2(100),
    valor_precatorio                NUMBER(18, 2),
    data_expedicao_precatorio       DATE,
    data_expedicao_precatorio_mask  VARCHAR2(10) GENERATED ALWAYS AS (CAST(mask_br_date(data_expedicao_precatorio) AS VARCHAR2(10))) VIRTUAL,
    nr_suplementar                  VARCHAR2(150),
    valor_suplementar               NUMBER(18, 2),
    data_expedicao_suplementar      DATE,
    data_expedicao_suplementar_mask VARCHAR2(10) GENERATED ALWAYS AS (CAST(mask_br_date(data_expedicao_suplementar) AS VARCHAR2(10))) VIRTUAL,

    -- devolução
    valor_devolvido                 NUMBER(18, 2),
    data_devolucao                  DATE,
    data_devolucao_mask             VARCHAR2(10) GENERATED ALWAYS AS (CAST(mask_br_date(data_devolucao) AS VARCHAR2(10))) VIRTUAL
);

SELECT * FROM processo_br;


/*
ALTER TABLE processo_br ADD (
    data_expedicao_precatorio_mask VARCHAR2(10) GENERATED ALWAYS AS (CAST(mask_br_date(data_expedicao_precatorio) AS VARCHAR2(10))) VIRTUAL,
    data_expedicao_suplementar_mask VARCHAR2(10) GENERATED ALWAYS AS (CAST(mask_br_date(data_expedicao_suplementar) AS VARCHAR2(10))) VIRTUAL,
    data_devolucao_mask VARCHAR2(10) GENERATED ALWAYS AS (CAST(mask_br_date(data_devolucao) AS VARCHAR2(10))) VIRTUAL
    );


*/
