-- truncate table ticket;

DROP TABLE ticket;
CREATE TABLE ticket
(
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tenant_code VARCHAR2(50) NOT NULL,
    tenant_id   INTEGER,
    title       VARCHAR2(100),
    status      VARCHAR2(20),
    open_date   DATE,
    due_date    DATE,
    done_date   DATE,
    description CLOB,
    urgent      NUMBER DEFAULT 0
);

SELECT * FROM ticket;