DROP TABLE wksp_sindicatto.email_queue;

CREATE TABLE wksp_sindicatto.email_queue
(
    id                 NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT email_queue_pk PRIMARY KEY,

    email_campaign_id  NUMBER,
    member_id          NUMBER,
    member_insert_date DATE,
    person_id          NUMBER,

    email              VARCHAR2(255) NOT NULL,

    status             VARCHAR2(20) DEFAULT 'pending',
    last_try           DATE,
    opened_at          DATE,

    name               VARCHAR2(255),
    company            VARCHAR2(100),
    home_uf            CHAR(2),
    work_uf            CHAR(2),

    blocked            NUMBER(1) DEFAULT 0,
    priority           NUMBER DEFAULT 10,

    error              CLOB,

    created_at         DATE DEFAULT SYSDATE,

    CONSTRAINT email_queue_status_ck
        CHECK (status IN ('pending', 'sent', 'error', 'invalid_email', 'processing')),

    CONSTRAINT email_queue_blocked_ck
        CHECK (blocked IN (0, 1)),

    CONSTRAINT email_queue_campaign_fk
        FOREIGN KEY (email_campaign_id)
        REFERENCES wksp_sindicatto.email_campaign (id)
);
/

CREATE INDEX wksp_sindicatto.email_queue_email_idx
    ON wksp_sindicatto.email_queue (email);
/

CREATE INDEX wksp_sindicatto.email_queue_member_insert_date_idx
    ON wksp_sindicatto.email_queue (member_insert_date);
/

CREATE INDEX wksp_sindicatto.email_queue_status_idx
    ON wksp_sindicatto.email_queue (status);
/

CREATE INDEX wksp_sindicatto.email_queue_campaign_idx
    ON wksp_sindicatto.email_queue (email_campaign_id);
/