DROP TABLE convenio;
CREATE TABLE convenio (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(255),
    html_regulamento CLOB,
    html_associado CLOB,
    active NUMBER(1)
);

