DROP TABLE wksp_sindicatto.email_blacklist;
CREATE TABLE wksp_sindicatto.email_blacklist
(
    id         number GENERATED BY DEFAULT ON NULL AS IDENTITY
        CONSTRAINT pk_email_blacklist PRIMARY KEY,

    email      varchar2(255),
    reason     clob,
    created_at timestamp DEFAULT current_timestamp,

    CONSTRAINT uq_email_blacklist_email UNIQUE (email)
);
/

SELECT * FROM wksp_sindicatto.email_blacklist;