CREATE TABLE ctype
(
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR2(50) NOT NULL,
    code VARCHAR2(100),
    id_perfil_old NUMBER,
    tag_perfil_old VARCHAR2(100),
    name VARCHAR2(50) NOT NULL,
    plural_name VARCHAR2(50) NOT NULL,
    description VARCHAR2(200),
    read_only NUMBER(1) DEFAULT 1 NOT NULL,
    is_admin NUMBER(1) DEFAULT 1 NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    hash AS (ORA_HASH("CODE")),
    CONSTRAINT uk_ctype_tenant_code UNIQUE (tenant_code, code)
)
/