prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/user_interface.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/has_page_access_permission_20260704_2341.sql
@@application/shared_components/security/app_access_control/manager.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/internal_login_check.sql
@@application/shared_components/logic/application_processes/date_brazil.sql
@@application/shared_components/logic/application_items/g_cpf_hash.sql
@@application/shared_components/logic/application_items/g_entity_id.sql
@@application/shared_components/logic/application_items/g_entity_name.sql
@@application/shared_components/logic/application_items/g_etype_code.sql
@@application/shared_components/logic/application_items/g_etype_name.sql
@@application/shared_components/logic/application_items/g_member_id.sql
@@application/shared_components/logic/application_items/g_password.sql
@@application/shared_components/logic/application_items/g_tenant_code.sql
@@application/shared_components/logic/application_items/g_tenant_code_lower.sql
@@application/shared_components/logic/application_items/g_tenant_id.sql
@@application/shared_components/logic/application_items/g_tenant_logo_url.sql
@@application/shared_components/logic/application_items/g_tenant_name.sql
@@application/shared_components/logic/application_items/g_username.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/desktop_theme_styles.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_due.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_initiated.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_priority.sql
@@application/shared_components/user_interface/lovs/unified_task_list_lov_type.sql
@@application/shared_components/user_interface/lovs/user_theme_preference.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_09998.sql
@@application/pages/page_09999.sql
@@application/pages/page_10000.sql
@@application/pages/page_10010.sql
@@application/pages/page_10020.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
