-- todo 20250712 deveria chamar tenant_etype
DROP TABLE etype CASCADE CONSTRAINTS;
CREATE TABLE etype (
    id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    tenant_code    VARCHAR2(50)        NOT NULL,
    --
    hash           INT GENERATED ALWAYS AS (ORA_HASH(code)) VIRTUAL,
    code           VARCHAR2(20),
    id_perfil_old  INTEGER,
    tag_perfil_old VARCHAR2(30),
    name           VARCHAR2(50)        NOT NULL,
    plural_name    VARCHAR2(50)        NOT NULL,
    description    VARCHAR2(200),
    read_only      NUMBER(1) DEFAULT 1 NOT NULL,
    is_admin       NUMBER(1) DEFAULT 1 NOT NULL,
    active         NUMBER(1) DEFAULT 1 NOT NULL,
    --
    CONSTRAINT uk_etype_tenant_code UNIQUE (tenant_code, code)
);

INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('SINDICATTO', 'admin', 1, 'admin', 'Administrador', 'Administradores', '', 0, 1);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANPPREV', 'admin', 1, 'admin', 'Administrador', 'Administradores', '', 0, 1);


-- Inserir tipos de entidade
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASACLUB', 'admin', 1, 'admin', 'Administrador', 'Administradores', 'Gestor do sistema, responsável por gerenciar os usuários e os acessos.', 0, 1);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASACLUB', 'partner_company', 3, 'empresa-parceira', 'Empresa Parceira', 'Empresas Parceiras', 'Empresa que é parceira da empresa.', 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASACLUB', 'staff', 4, 'entidade', 'Funcionário', 'Funcionários', 'Pessoa que é funcionária de uma empresa.', 0, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASACLUB', 'customer_support', 13, 'atendimento-asaclub', 'Atendente', 'Atendentes', 'Responsável por atender os clientes e resolver problemas técnicos.', 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASACLUB', 'marketing', 14, 'marketing', 'Marketing', 'Marketing', 'Responsável por promover a empresa e seus produtos.', 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASACLUB', 'agreement_analyst', 15, 'analista-de-convenios', 'Analista', 'Analistas', 'Responsável por gerenciar os convênios e acordos entre a empresa e os seus parceiros.', 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASACLUB', 'associate', 17, 'associado', 'Associado', 'Associados', 'Pessoa física ou jurídica que é associada a uma empresa parceira.', 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASACLUB', 'vip_lounge_service', 18, 'atendimento-vouchers', 'Atendente VIP', 'Atendentes VIP', 'Responsável por atender os clientes VIP.', 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASACLUB', 'temporary_access', 20, 'acesso-temporario', 'Acesso temporário', 'Acessos temporários', 'Acesso temporário para uma empresa ou pessoa.', 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASACLUB', 'dependent', 30, 'dependente', 'Dependente', 'Dependentes', 'Pessoa que é dependente de um associado.', 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASACLUB', 'staff_view', 32, 'entidade-visualizacao', 'Funcionário (só leitura)', 'Funcionários (só leitura)', 'Pessoa que é funcionária de uma empresa, com acesso somente leitura.', 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASACLUB', 'financial', 9, 'financeiro', 'Financeiro', 'Financeiro', '', 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASACLUB', 'director', 9, 'diretor', 'Diretor', 'Diretores', '', 1, 0);

--
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ADEPDF', 'associate', 17, 'associado', 'Associado', 'Associados', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ADEPDF', 'dependent', 30, 'dependente', 'Dependente', 'Dependentes', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ADEPDF', 'staff', 4, 'entidade', 'Funcionário', 'Funcionários', NULL, 0, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ADPF', 'associate', 17, 'associado', 'Associado', 'Associados', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ADPF', 'dependent', 30, 'dependente', 'Dependente', 'Dependentes', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ADPF', 'staff', 4, 'entidade', 'Funcionário', 'Funcionários', NULL, 0, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ADPF', 'staff_view', 32, 'entidade-visualizacao', 'Funcionário (só leitura)', 'Funcionários (só leitura)', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('AJUFER', 'associate', 17, 'associado', 'Associado', 'Associados', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('AJUFER', 'dependent', 30, 'dependente', 'Dependente', 'Dependentes', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('AJUFER', 'staff', 4, 'entidade', 'Funcionário', 'Funcionários', NULL, 0, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('AMATRA', 'associate', 17, 'associado', 'Associado', 'Associados', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('AMATRA', 'staff', 4, 'entidade', 'Funcionário', 'Funcionários', NULL, 0, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('AMPCON', 'associate', 17, 'associado', 'Associado', 'Associados', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('AMPCON', 'staff', 4, 'entidade', 'Funcionário', 'Funcionários', NULL, 0, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANADEF', 'associate', 17, 'associado', 'Associado', 'Associados', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANADEF', 'dependent', 30, 'dependente', 'Dependente', 'Dependentes', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANADEF', 'staff', 4, 'entidade', 'Funcionário', 'Funcionários', NULL, 0, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANAJUR', 'associate', 17, 'associado', 'Associado', 'Associados', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANAJUR', 'dependent', 30, 'dependente', 'Dependente', 'Dependentes', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANAJUR', 'staff', 4, 'entidade', 'Funcionário', 'Funcionários', NULL, 0, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANAUNI', 'associate', 17, 'associado', 'Associado', 'Associados', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANAUNI', 'dependent', 30, 'dependente', 'Dependente', 'Dependentes', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANAUNI', 'staff', 4, 'entidade', 'Funcionário', 'Funcionários', NULL, 0, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANPM', 'associate', 17, 'associado', 'Associado', 'Associados', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANPM', 'dependent', 30, 'dependente', 'Dependente', 'Dependentes', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANPM', 'staff', 4, 'entidade', 'Funcionário', 'Funcionários', NULL, 0, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANPPREV', 'associate', 17, 'associado', 'Associado', 'Associados', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANPPREV', 'dependent', 30, 'dependente', 'Dependente', 'Dependentes', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANPPREV', 'staff', 4, 'entidade', 'Funcionário', 'Funcionários', NULL, 0, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANPR', 'associate', 17, 'associado', 'Associado', 'Associados', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANPR', 'dependent', 30, 'dependente', 'Dependente', 'Dependentes', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANPR', 'staff', 4, 'entidade', 'Funcionário', 'Funcionários', NULL, 0, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ANPR', 'staff_view', 32, 'entidade-visualizacao', 'Funcionário (só leitura)', 'Funcionários (só leitura)', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('APDF', 'associate', 17, 'associado', 'Associado', 'Associados', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('APDF', 'dependent', 30, 'dependente', 'Dependente', 'Dependentes', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('APDF', 'staff', 4, 'entidade', 'Funcionário', 'Funcionários', NULL, 0, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASABNB', 'associate', 17, 'associado', 'Associado', 'Associados', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASABNB', 'dependent', 30, 'dependente', 'Dependente', 'Dependentes', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASABNB', 'staff', 4, 'entidade', 'Funcionário', 'Funcionários', NULL, 0, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASCGU', 'associate', 17, 'associado', 'Associado', 'Associados', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASLEGIS', 'associate', 17, 'associado', 'Associado', 'Associados', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASLEGIS', 'dependent', 30, 'dependente', 'Dependente', 'Dependentes', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('ASLEGIS', 'staff', 4, 'entidade', 'Funcionário', 'Funcionários', NULL, 0, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('AUDITAR', 'associate', 17, 'associado', 'Associado', 'Associados', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('AUDITAR', 'dependent', 30, 'dependente', 'Dependente', 'Dependentes', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('AUDITAR', 'staff', 4, 'entidade', 'Funcionário', 'Funcionários', NULL, 0, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('INATTO', 'admin', 1, 'admin', 'Administrador', 'Administradores', NULL, 0, 1);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('INATTO', 'staff', 4, 'entidade', 'Funcionário', 'Funcionários', NULL, 0, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('INFRAMERICA', 'vip_lounge_service', 18, 'atendimento-vouchers', 'Atendente VIP', 'Atendentes VIP', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('SINPROFAZ', 'associate', 17, 'associado', 'Associado', 'Associados', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('SINPROFAZ', 'dependent', 30, 'dependente', 'Dependente', 'Dependentes', NULL, 1, 0);
INSERT INTO etype (tenant_code, code, id_perfil_old, tag_perfil_old, name, plural_name, description, read_only, is_admin) VALUES ('SINPROFAZ', 'staff', 4, 'entidade', 'Funcionário', 'Funcionários', NULL, 0, 0);

--
SELECT *
FROM etype
order by tenant_code, code
/