SELECT
    M.ID AS MEMBER_ID,
    E.ID AS ENTITY_ID,
    REGEXP_REPLACE(E.BR_CPF, '[^0-9]', '') AS CPF,
    E.NAME AS NOME,
    M.BR_SIAPE AS SIAPE,
    M.BR_SITUACAO_FUNCIONAL_CODE,
    M.BR_SITUACAO_ASSOCIATIVA_CODE,
    M.ACTIVE,
    M.IMPORT_FILE_NAME
FROM WKSP_SINDICATTO.MEMBER M
JOIN WKSP_SINDICATTO.ENTITY E
     ON E.ID = M.ENTITY_ID
WHERE M.TENANT_CODE = 'anpprev'
    AND M.ETYPE_CODE = 'associate'
    AND M.IMPORT_FILE_NAME =
    '20260721_Relação de associados_atualizada.xlsx'
ORDER BY CPF, M.ID;