SELECT
    M.ID AS MEMBER_ID,
    E.ID AS ENTITY_ID,
    REGEXP_REPLACE(E.BR_CPF, '[^0-9]', '') AS CPF,
    TRIM(E.NAME) AS NOME,
    TRIM(M.BR_SIAPE) AS SIAPE,
    M.BR_SITUACAO_FUNCIONAL_CODE,
    M.BR_SITUACAO_FUNCIONAL_NAME,
    M.BR_SITUACAO_ASSOCIATIVA_CODE,
    M.BR_SITUACAO_ASSOCIATIVA_NAME,
    M.ACTIVE
FROM WKSP_SINDICATTO.MEMBER M
JOIN WKSP_SINDICATTO.ENTITY E
     ON E.ID = M.ENTITY_ID
WHERE LOWER(M.TENANT_CODE) = 'anpprev'
    AND LOWER(M.ETYPE_CODE) = 'associate'
ORDER BY CPF, M.ID;